### ISSUE TITLE
Change of module name

### ISSUE THREAD

**Issue by pdebuyl** [espressopp/espressopp#1]
Hi,

Following the discussion on the mailing-list http://theweb.mpip-mainz.mpg.de/pipermail/espp-users/2014-June/000047.html about espresso, espressomd and espressopp I suggested that http://espressomd.org/ be espressomd and http://www.espresso-pp.de/ be espressopp for the module names. espressomd did the move some time ago https://github.com/espressomd/espresso/commit/2eace0aaffdcd5e6aad9258711e12ab86f5e4ec3

I have applied a blind `sed -i -e 's/espresso/espressopp/g'` to all files and there was very little fixes to make. Should espressopp move to its unambiguous name?

**Comment by stuehn** [comment]
Hi Pierre,

yes, I remember that this task was still on my TODO list :-)

If you could do some tests and make sure that everything is still working
I would fully support your step.
Users that don't want to change their python scripts just have to
change "import espresso" to "import espressopp as espresso" which should be fine.

Best,
Torsten

On 03/16/2015 10:16 AM, Pierre de Buyl wrote:
> Hi,
>
> Following the discussion on the mailing-list
> http://theweb.mpip-mainz.mpg.de/pipermail/espp-users/2014-June/000047.html
> about espresso, espressomd and espressopp I suggested that
> http://espressomd.org/ be espressomd and http://www.espresso-pp.de/
> be espressopp for the module names. espressomd did the move some time
> ago espressomd/espresso@2eace0a
> <https://github.com/espressomd/espresso/commit/2eace0aaffdcd5e6aad9258711e12ab86f5e4ec3>
>
>  I have applied a blind |sed -i -e 's/espresso/espressopp/g'| to all
> files and there was very little fixes to make. Should espressopp move
> to its unambiguous name?
>
> — Reply to this email directly or view it on GitHub
> <https://github.com/espressopp/espressopp/issues/1>.
>

-- 
Max Planck Institute for Polymer Research
Dr. Torsten Stuehn (Head of IT)
Ackermannweg 10
55128 Mainz / Germany
phone +49-(0)6131-379268

**Comment by pdebuyl** [comment]
I have made the change here: https://github.com/pdebuyl/espressopp/tree/rename

I have run several of the examples and testsuite programs with success.

**Comment by pdebuyl** [comment]
PS: I don't know what the versioning guidelines are for espressopp but a minor version bump would be good to let users know about the change.

**Comment by junghans** [comment]
Hmm, sorry to interrupt this effort, but after http://espressomd.org/ has renamed its module to `espressomd`, what is the point of renaming ours?

**Comment by stuehn** [comment]
As far as I remember both package maintainers agreed to change their respective name.
It wouldn't be nice behavior if we suddenly decided to keep ours.
In addtion I think "espressopp" does fit better to "ESPResSo++" than "espresso".
Renaming to "espressopp" also helps people to understand that "ESPResSo" and "ESPResSo++"
are two different packages.

I'm still in favor of renaming the python-module to "espressopp"

Best,
Torsten

On 03/16/2015 04:27 PM, Christoph Junghans wrote:
> Hmm, sorry to interrupt this effort, but after http://espressomd.org/ has renamed its module to |espressomd|, what is the point of renaming ours?
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/espressopp/espressopp/issues/1#issuecomment-81736802>.
>

-- 
Max Planck Institute for Polymer Research
Dr. Torsten Stuehn (Head of IT)
Ackermannweg 10
55128 Mainz / Germany
phone +49-(0)6131-379268

**Comment by junghans** [comment]
From the email thread above, I don't see that any real decision was made on the espresso++ side, beside you saying: *I could live with this solution.* ;-)

Anyhow, as renaming the module to `espressopp` sound good to me. Please see pull request #2 for the actual changes.

**Comment by MrTheodor** [comment]
On 16 March 2015 at 15:36, Pierre de Buyl <notifications@github.com> wrote:

> PS: I don't know what the versioning guidelines are for espressopp but a
> minor version bump would be good to let users know about the change.
>
>
Very good point. I would go even one step further and in the next release
put warning that using espresso is deprecated and the name will change to
espressopp. Perhaps internally it will be possible to keep two names for
the next release by symlink. I think that otherwise people could be
confused.

Best, Jakub
