### ISSUE TITLE
make install does not copy Python code to dist-packages

### ISSUE THREAD

**Issue by MrTheodor** [espressopp/espressopp#11]
After `make install` there is no way to use `espressopp` module. Mainly the Python files are missing in `/dist-packages/` and only `_espressopp.so` is copied.

**Comment by pdebuyl** [comment]
I never used `make install` with espressopp. All the `.py` and `.pyc` files should be copied in a directory espressopp in site-package (or dist-package for .deb files) along with `_espressopp.so`.

Is anyone really installing espressopp?

**Comment by junghans** [comment]
`make install` is suppose to work, I just forgot to re-add it after the clean up of the build system.

**Comment by MrTheodor** [comment]
Great, thanks!

@pdebuyl Well I tried to prepare share package with different compilers on cluster. Perhaps I could also clone repository.
