### ISSUE TITLE
Python 2 and Python 3. No xrange() function in Python 3

### ISSUE THREAD

**Issue by fedepad** [espressopp/espressopp#111]
Related to #97 , I know that probably that change has been done for speed reasons most probably, especially in the case of repeated loops or many many iterations (e.g. for idx in xrange(num_particles)).
But I wanted to point out that this change is ok until we keep running with Python 2.
If we ever plan in the far away future to run with Python 3, this would need to be changed when running with Python 3.
The reason, which I think many might be familiar, is that there's no xrange() in Python 3 since its place has been taken by range() (the way was working xrange() in contrast to range() in Python 2 is equivalent to range() in Python 3 and there's no xrange()) and more features have been added. 
So almost (because extra features, so can add extra overhead; xrange looks still faster in repeated loops on my system; for # iteration ~10000 speed difference seems very small) similar behavior and speed (cum grano salis) for that in Python 3 are achieved by just using range().

Just for reference, I link to the source code for the implementation of the range() functions in Python 2/3; you can see in the Python 3 version there's no mention of xrange.
https://hg.python.org/cpython/file/2.7/Objects/rangeobject.c
https://hg.python.org/cpython/file/3.3/Objects/rangeobject.c

And to this nice posts on SO:
http://stackoverflow.com/questions/94935/what-is-the-difference-between-range-and-xrange-functions-in-python-2-x
http://stackoverflow.com/questions/15014310/why-is-there-no-xrange-function-in-python3

**Comment by MrTheodor** [comment]
Sure, but that's easy to revert change. Python 2.7 will end its life in 2020 so there is still some time to migrate ;)

**Comment by fedepad** [comment]
Oh yes, sure, I was just reading on the Python 2/3 changes and the xrange/range was there and I remember there was a PR on that, so I was curious and kept reading the SO posts on that, just that, and then I tried on my system! ;)

**Comment by ault2910** [comment]
you will get this error NameError: global name ‘xrange’ is not defined in Python 3. better to use range(). in Python 3.x xrange is deprecated now. see [https://pynative.com/python-xrange-vs-range/](url)
