### ISSUE TITLE
Release control strategy

### ISSUE THREAD

**Issue by niktre** [espressopp/espressopp#118]
Hi everybody.
I just want to sum up some things happening in the last time here. Starting from 1st of November I will be a full-time ESPResSo++ developer, who should take care of the project, mainly in these areas:
- Management (release control, how-to practices, etc.)
- Software development (new and standard methods, new architectures)
- Visibility (docs, website, publications)

I want that we start a bit earlier and develop a proper (not perfect) release control and communication strategy. In the last couple of days I was playing with the tab "Projects", with Milestones, Labels, etc. that may have annoyed you. Of course, I was also trying to talk to some of you to share ideas. So here I would like to present and **DISCUSS** the strategy that at the moment seems to be the most promising one.

**Comment by niktre** [comment]
**Step 1.** We need to fill in the board `Release Plan`. There will be 3 lists: `v.1.9.5`, `v2.0` and `v3.0` that stand for short-, mid- and long-term release versions, correspondingly. They will be filled with **notes** on what has to be in the corresponding version of EPP (not to confuse with the band "Emergency Pizza Party"!). The farther the release version the more general and vague a note can be. For example: 

- "Port some modules to GPU" --> `v3.0`, 

- "Make proper documentation" --> `v2.0` and 

- "Make copyright changes to all the files" or "fix singularity in tabulated torsion potential at angles 0 and 180" --> `v1.9.5`. 
This step has to be communicated with and approved by @stuehn and @KurtKremer.

**Step 2.** Since we know now the strategy, we can start to use Milestones using `Release Plan` as a guide. The milestones are labeled as `v.1.9.5`, `v2.0` and `v3.0` as well. They have to be assigned to every **issue** or **pull request** we create. Do you see what your current issue is related to? Put the same Milestone on it. Can not associate it with anything? Assign the milestone of the short-term version. For example:

- I opened the issue "Fix singularity by analytical cosine expansion" and assigned immediately milestone `v1.9.5` to it.

- I opened the pull request "Documented 10 interactions" and assigned milestone `v2.0` to it.

- I opened the pull request "Lees-Edwards boundary conditions for shear flow" and assigned milestone `v1.9.5` to it, as there is nothing in the "Release Plan" on such boundary conditions.

 Why bother like this? Because then we can track by Milestones how far are we from the next release (in %) and know what to work on (or shift a feature to the later release). 

**Step 3.** After milestones are set we can monitor our current production workload - `Workload` board with the lists `Backlog`, `In Progress`, `In Review` and `Done` (the last one is actually not needed, but it is nice just to see that some work was done).

- Every issue with the Milestone of the short-term version goes into the `Backlog` as an interactive card (bugs + enhancements). If you plan to work on some enhancement in the near future but do not want to create an issue, put it into the `Backlog` as a **note**. Why? To show your intention to the other developers.

- Started to work on something from the `Backlog`? Move a card or note to `In Progress`.

- Opened a pull request? Move the card (or convert a note into a card) and put it in `In Review`

In the end, **Step 1** will be done every several month and will take some time at first. **Step 2** asks you to put a milestone on every bug or enhancement issue you open (or on pull requests) consulting the `Release Plan`. **Step 3** is there to monitor the progress and communicate your development plans with others. 

How do you find it? Too complicated?

**Comment by govarguz** [comment]
@niktre, I gave my input during the planning and discussion. I find it OK!

**Comment by acfogarty** [comment]
Looks great to me! 

Of course, since for many of us what we implement is dictated by our scientific research projects, and since the schedules for these projects are dictated by external factors completely unrelated to espressopp, we'll have to be flexible about shifting features back and forth between different versions. Other than that, everything looks great.

What about where we actually keep code? e.g. I would have In Progress code in a local repository and not push it anywhere on github until actually making a PR to espressopp/espressopp master. Other developers seem to be keeping such In Progress code in branches of their github forks. I guess each person can decide that for himself?

**Comment by MrTheodor** [comment]
@niktre nice work!, 
if I understood correctly, issues would be assigned to releases according to the ```release plan```, but what with the hotfixes that could appear at any time? Perhaps there should be a separate column in ```workload``` to handle it.

**Comment by niktre** [comment]
@acfogarty you are right about shifting. The `Release Plan` should not be carved in stone and is rather a guideline.

About place to code. It is related to issue #26. There @pdebuyl shared a link to ViennaRSS:
https://github.com/ViennaRSS/vienna-rss/wiki/Good-manners-with-Git
Look at the sections "One time setup" and "Day to day work". The first "Problem" afterwards indicates why people use branches and make commits (and pushes) to them. 

Though this strategy is not the only one that can work, it seems very reasonable to me. If you commit to a local repository and are satisfied with this then just do it like this. Maybe it is a reasonable approach if you are working on a secret scientific project :-)

**Comment by niktre** [comment]
@MrTheodor thanks!

It is true, the issues will be assigned according to the `Release Plan`. The issues that are hotfixes should be marked as bugs (red label) and get the short-term milestone `v1.9.5`. After issue is added one has to create a card for it in the `Workload` (not to the `Release Plan`) and it will be already marked with bug label and ideally attract people's attention. Ideally you are right, one needs a separate column for this, but the number of issues marked as bugs is very small and we can escape without such column.

Or did I misunderstand the question?

**Comment by fedepad** [comment]
@niktre Great work! I need to read a couple of times to make it stick on my mind, but great!
