### ISSUE TITLE
Migrate deprecated boost signals template

### ISSUE THREAD

**Issue by MrTheodor** [espressopp/espressopp#125]
Currently the signals are defined with templates `signal0`, `signal2`. This is required because the template support in old compilers does not allows to have variable number of arguments.
Here from [boost library](http://www.boost.org/doc/libs/1_61_0/doc/html/signals2/api_changes.html):

> Version 1.40 also introduces a variadic templates implementation of Signals2, which is used when Boost detects compiler support for variadic templates (variadic templates are a new feature of C++11). This change is mostly transparent to the user, however it does introduce a few visible tweaks to the interface as described in the following.
> 
> The following library features are deprecated, and are only available if your compiler is NOT using variadic templates (i.e. BOOST_NO_CXX11_VARIADIC_TEMPLATES is defined by Boost.Config).
> 
> The "portable syntax" signal and slot classes, i.e. signals2::signal0, signal1, etc.
> 
> The arg1_type, arg2_type, etc. member typedefs in the signals2::signal and signals2::slot classes. They are replaced by the template member classes signals2::signal::arg and signals2::slot::arg.

The change will be very easy, e.g.
`boost::signals2::signal2 <void, ParticleList&, class OutBuffer&>`
to
`boost::signals2::signal<void (ParticleList&, class OutBuffer&)>`

This change will cause that the compiler has to support c++1x standard.

http://www.boost.org/doc/libs/1_61_0/doc/html/signals2.html

**Comment by junghans** [comment]
Fix by #166.
