### ISSUE TITLE
E++ package for Spack package manager for HPC

### ISSUE THREAD

**Issue by fedepad** [espressopp/espressopp#130]
Hi all,

yesterday I wrote the E++ package recipe for the Spack package manager for HPC (https://github.com/LLNL/spack).
Actually I'm almost done, I can build on OSX and Linux (Debian) but I want to test it when also other options (like docs, specific versions of the libraries, compilers) are desired by the user and try to run one example; still I have to understand a couple of things.

I was thinking about getting into the main tree. Thoughts?
Otherwise it will be available from my fork.

The non-updated version of what I put together yesterday can be found here:
https://github.com/fedepad/spack/tree/features/espressopp

but still needs some work.
Since many scientific and non packages are there or getting there I think would be a nice addition.

**Comment by junghans** [comment]
This is now LLNL/spack#2602.

**Comment by fedepad** [comment]
Ok, thanks, I just synchronized it to the latest develop they have.

**Comment by fedepad** [comment]
Dear all, just to update on this in case you've not followed...
Many of the changes that were requested are in, and with a bit more of review on their part and maybe few more changes on my part, I expect that "soon" the package recipe for E++ will go in!
