### ISSUE TITLE
codecov in docker

### ISSUE THREAD

**Issue by niktre** [espressopp/espressopp#145]
@junghans 
I've found in codecov docs that it is possible to run tests inside a Docker container [see here](http://docs.codecov.io/docs/testing-with-docker). Could you explain the difference with our current codecov strategy?

**Comment by junghans** [comment]
It is already done in `COVERAGE=ON` build with gcc:
https://travis-ci.org/espressopp/espressopp/jobs/184544722#L2290

Something is broken for clang though.

**Comment by junghans** [comment]
I think for llvm coverage we need to call  `codecov --gcov-exec ${GCOV}` with `GCOV=llvm-cov gcov`.
