### ISSUE TITLE
Drop some coverage builds

### ISSUE THREAD

**Issue by junghans** [espressopp/espressopp#148]
I seems ccache doesn't play well with coverage and hence these builds take 26min instead of the usual 7min.

We are currently doing 8 builds (2 compiler * 2 mpi variants * 2 distributions), but 2 builds might be enough as mpi and distribution won't change the coverage rate anyhow.

**Comment by junghans** [comment]
@niktre: any opinion?

**Comment by niktre** [comment]
I do not have a strong argument, but I would keep 2 mpi variants and go to 1 distribution, so that we have 4 builds in total

**Comment by junghans** [comment]
I seems to me the mpi variants won't change the coverage, but the Linux distribution might due to different compilers.

**Comment by niktre** [comment]
good, it makes sense
