### ISSUE TITLE
Hard-coded timer array size causes random seg fault

### ISSUE THREAD

**Issue by acfogarty** [espressopp/espressopp#154]
In VelocityVerlet.hpp, the array timeForceComp is hard-coded to size of 100. If a system has more interactions than the size of timeForceComp, random segmentation faults will occur. 

Temporary hack solution: increase size of array so it's less likely the problem will occur.

Long-term solution: apparently @govarguz has a new and better timer setup that will someday be integrated into VelocityVerlet class.

The timers in VelocityVerlet are hard-coded for the bead-spring system, containing only interactions LJ+FENE+angle, so need to be rewritten someday anyway.

@stuehn 

See PR #155

**Comment by junghans** [comment]
The real solution would be to use something like [Caliper](https://github.com/LLNL/Caliper) instead of reinventing the wheel, @fedepad should know how to use it.

**Comment by XzzX** [comment]
PR was merged.
