### ISSUE TITLE
Espresso++ in Spack: report of first experiences

### ISSUE THREAD

**Issue by fedepad** [espressopp/espressopp#161]
A while ago, I wrote the E++ recipe for the Spack package manager that has been committed to the main repo at https://github.com/LLNL/spack/pull/2602 and was addressing #130 .

Briefly I wanted to report the first real experience with that, which some people found pretty cool and easy to just run, as sometimes there have been building issues with dependencies.

Once one git clone Spack and put the bin dir into the PATH to get autocompletion, with a couple of lines for configuration one is basically good to go and just do:

`spack install espressopp`

and espressopp will be installed and ALL dependencies will be taken care of. 
Notice that you can specify basically ANY (that satisfy version requirements) compiler version,  espressopp version (only recents are in, you can look the code), boost, mpi, python, cmake, etc. on the command line.
In this case it will install espressopp 1.9.4.1 as it's the newest stable version (one can also use `spack install espressopp@develop` to install the master branch version) and create module files, which are commonly used in many Linux HPC clusters to provide software for people.
Once is done with all dependencies and the main package one can just do

`module load espressopp/1.9.4.1-gcc-4.4.7-i4fik4h` 
and automagically all the right dependencies used for building the version are autoloaded:

> Autoloading python/2.7.13-gcc-4.4.7-xv7nrjp
> Autoloading bzip2/1.0.6-gcc-4.4.7-lhojphl
> Autoloading ncurses/6.0-gcc-4.4.7-omk5gcj
> Autoloading zlib/1.2.11-gcc-4.4.7-sjoltdl
> Autoloading openssl/1.1.0e-gcc-4.4.7-qj3ldci
> Autoloading sqlite/3.8.5-gcc-4.4.7-xdbttkj
> Autoloading readline/6.3-gcc-4.4.7-lqzgyaq
> Autoloading openmpi/2.0.2-gcc-4.4.7-tfjhl2r
> Autoloading hwloc/1.11.5-gcc-4.4.7-nzvbmqd
> Autoloading libpciaccess/0.13.4-gcc-4.4.7-pu3ftqd
> Autoloading fftw/3.3.5-gcc-4.4.7-hwt4dbn
> Autoloading boost/1.63.0-gcc-4.4.7-r64dsvs
> Autoloading py-mpi4py/2.0.0-gcc-4.4.7-je5mjdv

Then on the shell to quickly check that the espressopp module is seen:
[padua@boron ~]$ python
Python 2.7.13 (default, Feb 23 2017, 00:48:12) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-17)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import espressopp
Warning: numpy module not available
>>> exit()

I did runs with Lennard Jones and they run fine to completion.

P.S.: I didn't know how to label this as there was no "report" label, so I just picked two... ;)

**Comment by junghans** [comment]
@fedepad: please have a look at: https://spack.readthedocs.io/en/latest/basic_usage.html#extensions-python-support

Does `spack activate py-numpy` fixes it?

**Comment by junghans** [comment]
Now called py-espressopp (LLNL/spack#5732)
