### ISSUE TITLE
.so file part of installation?

### ISSUE THREAD

**Issue by ocaisa** [espressopp/espressopp#167]
Similar to #161 I was putting E++ in [EasyBuild ](easybuild.readthedocs.org)and I noticed that the generated `_espressopp.so` file isn't part of the installation step.  Sorry if this is a silly question but I would've thought that you would have to  bring this library with your installation?

In general I don't see an installation step outlined in your documentation and I wonder if I am missing something? I can successfully import the installed python module, I just wonder if there is a runtime error waiting to pop up (and I don't have a test case to try it out)?

**Comment by junghans** [comment]
`_espressopp.so` is installed by cmake [here](https://github.com/espressopp/espressopp/blob/master/src/CMakeLists.txt#L48) and imported by many python scripts, so it will be needed.

**Comment by ocaisa** [comment]
Ah, yes, sorry, I was expecting it to sit directly in the `lib` directory, my mistake. Thanks!

BTW I saw someone from your project opened a [ticket for Boost 1.63.0](https://svn.boost.org/trac/boost/ticket/12993), I've built E++ with Boost 1.64.0 but Boost MPI required the patch from [this merged pull request](https://github.com/boostorg/mpi/pull/39) to build correctly.
