### ISSUE TITLE
installing espresso++ software error

### ISSUE THREAD

**Issue by NABIAHAMAD** [espressopp/espressopp#175]
Hello,
I am installing espresso++ software on a cluster then i got the error in installation given bellow

CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:97 (MESSAGE):
Could NOT find FFTW3 (missing: FFTW3_LIBRARIES FFTW3_INCLUDES)
Call Stack (most recent call first):
/usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:288 (_FPHSA_FAILURE_MESSAGE)
cmake/FindFFTW3.cmake:20 (find_package_handle_standard_args)
CMakeLists.txt:71 (find_package)

-- Configuring incomplete, errors occurred!
What i have to do, Can anyone please help?
Thanks

**Comment by MrTheodor** [comment]
CMake cannot find FFTW3 library, please check where the FFTW3 is installed on your cluster and provided direct path:

`cmake . -DFFTW3_LIBRARIES=/path/to/library.so -DFFTW3_INCLUDES=/path/to/include`

**Comment by NABIAHAMAD** [comment]
Dear sir,
when i am giving direct path which is written above then i stuck in another problem which is given below-
Found PythonInterp: /usr/local/bin/python2 (found suitable version "2.7.11", minimum required is "2") 
-- PYTHON_INCLUDE_PATH = /usr/local/include/python2.7
-- PYTHON_VERSION = 2.7
-- PYTHON_LIBDIR = /usr/local/lib
-- PYTHON_LIBRARIES = /usr/local/lib/libpython2.7.a
-- Looking for 3 include files sys/time.h, ..., unistd.h
-- Looking for 3 include files sys/time.h, ..., unistd.h - found
-- Could NOT find Boost
CMake Error at CMakeLists.txt:145 (message):
  Boost (required at least version ) not found, make sure you have installed
  boost and it's dev packages.  To hint cmake to your Boost installation, use
  the option -DBOOST_ROOT=/path/to/boost.  As last resort you can use our
  internal replacement with -DEXTERNAL_BOOST=OFF


-- Configuring incomplete, errors occurred!
What i have to do, Can anyone please help?
Thanks

**Comment by MrTheodor** [comment]
Exactly what CMake suggested, you can either put the path to `BOOST_ROOT` or use internal boost by adding flag `-DEXTERNAL_BOOST=OFF`

**Comment by MrTheodor** [comment]
@NABIAHAMAD  Is it solved?

**Comment by NABIAHAMAD** [comment]
Thank you Mr. Theodor for answered my question but still i did not install espresso++ software on my cluster account.
Thank you

**Comment by NABIAHAMAD** [comment]
I still get error in running:
>>> espressopp.tools.vmd.connect(system)
Does it need a clean vmd install?

**Comment by NABIAHAMAD** [comment]
Hello,
when i am running espresso++ command  
espressopp.tools.vmd.connect(system)
then i got the error which is given below
The new particle position is: 
Traceback (most recent call last):
  File "espresso.py", line 50, in <module>
    espressopp.tools.vmd.connect(system)
  File "/export/apps/espressopp/espressopp-1.9.4.1/espressopp/tools/vmd.py", line 144, in connect
    subprocess.Popen([vmd_path, '-e', 'vmd.tcl'])
  File "/share/apps/python-2.7/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/share/apps/python-2.7/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Does it need a clean vmd install?
What i have to do, Can anyone please help?
Thanks

**Comment by MrTheodor** [comment]
Please open a new issue, this nothing to do with your previous installation problem.
