### ISSUE TITLE
import espressopp

### ISSUE THREAD

**Issue by NABIAHAMAD** [espressopp/espressopp#183]
Hi,
When I  import espressopp in python then I got the message given below-
```
import espressopp
--------------------------------------------------------------------------
[[59756,1],0]: A high-performance Open MPI point-to-point messaging module
was unable to find any relevant network interfaces:

Module: OpenFabrics (openib)
  Host: pd

Another transport will be used instead, although this may result in
lower performance.
```
I want to know that it is an error/issue or what ? My code is working fine, let me know what I have to do.
Our cluster is a 1+5 node and each have octa core and dual processor.
Thank you

**Comment by junghans** [comment]
I just means, your MPI was compiled with `openib`, but the current compute node has no `openib` network interface, so MPI fails back to another network protocol.

This issue has nothing to do with espressopp, you might need to talk to your cluster administrator to fix the local MPI installation.
