### ISSUE TITLE
Problems when running ConstrainCOM in parallel

### ISSUE THREAD

**Issue by GDeichmann** [espressopp/espressopp#185]
I had a try at the new ConstrainCOM feature. However, running in parallel seems to be problematic. With me, the code runs into a deadlock every time I initialize a new `FixedLocalTupleListConstrainCOM` object in python using multiple nodes.
I ran a short printf-debugging of the c++ constructor and it seems that `num_of_subchain` has different values on each node before being passed to `boost::mpi::all_reduce` in line 127 in FixedLocalTupleComListInteractionTemplate.hpp . 
@hidekb

**Comment by MrTheodor** [comment]
Do you get some error message ?

**Comment by GDeichmann** [comment]
No the program just runs into a deadlock. Presumably, at the `all_reduce` statement mentioned above.

I already tried the new version proposed in pull request #186. With that everything runs smoothely and the forces on all particles are calculated correctly.

**Comment by hidekb** [comment]
Although you already know the pull request #186, I explain the origin of this problem.
When any CPU have empty ``FixedLocalTupleList``, `N_constrain` have never been determined uniquely or can't be determined. Hence, the calculation is terminated abnormally or is into deadlock.
The pull request #186 fixed this problem.
