### ISSUE TITLE
getting error on installation of espresso++ software 

### ISSUE THREAD

**Issue by NABIAHAMAD** [espressopp/espressopp#190]
Hello,
I am installing espresso++ software on a cluster locally, I do not have root password, then i got the error in make step after complete 76% which is given bellow-
```
/UHOME/nabia.dcy2014/espresso/espressopp-1.9.4.1/src/interaction/CoulombKSpaceP3M.hpp:510: error: expected type-specifier before ‘fftw_complex’
/UHOME/nabia.dcy2014/espresso/espressopp-1.9.4.1/src/interaction/CoulombKSpaceP3M.hpp:510: error: expected ‘>’ before ‘fftw_complex’
/UHOME/nabia.dcy2014/espresso/espressopp-1.9.4.1/src/interaction/CoulombKSpaceP3M.hpp:510: error: expected ‘(’ before ‘fftw_complex’
/UHOME/nabia.dcy2014/espresso/espressopp-1.9.4.1/src/interaction/CoulombKSpaceP3M.hpp:510: error: ‘fftw_complex’ was not declared in this scope
/UHOME/nabia.dcy2014/espresso/espressopp-1.9.4.1/src/interaction/CoulombKSpaceP3M.hpp:510: error: expected primary-expression before ‘>’ token
/UHOME/nabia.dcy2014/espresso/espressopp-1.9.4.1/src/interaction/CoulombKSpaceP3M.hpp:510: error: expected ‘)’ before ‘;’ token
/UHOME/nabia.dcy2014/espresso/espressopp-1.9.4.1/src/interaction/CoulombKSpaceP3M.hpp:512: error: ‘plan’ was not declared in this scope
/UHOME/nabia.dcy2014/espresso/espressopp-1.9.4.1/src/interaction/CoulombKSpaceP3M.hpp:512: error: ‘fftw_execute’ was not declared in this scope
/UHOME/nabia.dcy2014/espresso/espressopp-1.9.4.1/src/interaction/CoulombKSpaceP3M.hpp: In member function ‘bool espressopp::interaction::CoulombKSpaceP3M::_computeForce(espressopp::CellList)’:
/UHOME/nabia.dcy2014/espresso/espressopp-1.9.4.1/src/interaction/CoulombKSpaceP3M.hpp:534: error: ‘in_array’ was not declared in this scope
/UHOME/nabia.dcy2014/espresso/espressopp-1.9.4.1/src/interaction/CoulombKSpaceP3M.hpp:534: error: expected type-specifier before ‘fftw_complex’
/UHOME/nabia.dcy2014/espresso/espressopp-1.9.4.1/src/interaction/CoulombKSpaceP3M.hpp:534: error: expected ‘>’ before ‘fftw_complex’
/UHOME/nabia.dcy2014/espresso/espressopp-1.9.4.1/src/interaction/CoulombKSpaceP3M.hpp:534: error: expected ‘(’ before ‘fftw_complex’
/UHOME/nabia.dcy2014/espresso/espressopp-1.9.4.1/src/interaction/CoulombKSpaceP3M.hpp:534: error: ‘fftw_complex’ was not declared in this scope
/UHOME/nabia.dcy2014/espresso/espressopp-1.9.4.1/src/interaction/CoulombKSpaceP3M.hpp:534: error: expected primary-expression before ‘>’ token
/UHOME/nabia.dcy2014/espresso/espressopp-1.9.4.1/src/interaction/CoulombKSpaceP3M.hpp:534: error: expected ‘)’ before ‘;’ token
/UHOME/nabia.dcy2014/espresso/espressopp-1.9.4.1/src/interaction/CoulombKSpaceP3M.hpp:536: error: ‘plan’ was not declared in this scope
/UHOME/nabia.dcy2014/espresso/espressopp-1.9.4.1/src/interaction/CoulombKSpaceP3M.hpp:536: error: ‘fftw_execute’ was not declared in this scope
make[2]: *** [src/CMakeFiles/_espressopp.dir/interaction/CoulombKSpaceP3M.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/_espressopp.dir/all] Error 2
make: *** [all] Error 2
```

What i have to do, Can anyone please help?
Thanks

**Comment by junghans** [comment]
Something is wrong with your fftw installation. What version of fftw are you using?

**Comment by NABIAHAMAD** [comment]
Hi,
I am using fftw-3.3.4 version
Thank you

**Comment by junghans** [comment]
Hmm, 3.3.4 should be ok. Can you upload log of the whole build incl. cmake:
```bash
bash
cmake <YOUR OPTIONS HERE> 2>&1 | tee log.txt
cat CMakeCache.txt | tee -a log.txt
make 2>&1 | tee -a log.txt
```
and attach the `log.txt` to your next comment.

**Comment by NABIAHAMAD** [comment]
Hello,
My fftw problem have solved but another error is coming on make step as-
**/UHOME/nabia.dcy2014/espresso/espressopp-1.9.4.1/src/integrator/LBInitPopUniform.cpp:52:2: warning: #warning : check if taking care of OFFSET AT INITIALISATION () is needed**
[ 68%] Building CXX object src/CMakeFiles/_espressopp.dir/integrator/LBInitPopWave.cpp.o
[ 68%] Building CXX object src/CMakeFiles/_espressopp.dir/integrator/LGLatticeSite.cpp.o
[ 68%] Building CXX object src/CMakeFiles/_espressopp.dir/integrator/LangevinBarostat.cpp.o
[ 69%] Building CXX object src/CMakeFiles/_espressopp.dir/integrator/LangevinThermostat.cpp.o
[ 69%] Building CXX object src/CMakeFiles/_espressopp.dir/integrator/LangevinThermostat1D.cpp.o
[ 69%] Building CXX object src/CMakeFiles/_espressopp.dir/integrator/LangevinThermostatHybrid.cpp.o
[ 70%] Building CXX object src/CMakeFiles/_espressopp.dir/integrator/LangevinThermostatOnGroup.cpp.o
[ 70%] Building CXX object src/CMakeFiles/_espressopp.dir/integrator/LatticeBoltzmann.cpp.o
/UHOME/nabia.dcy2014/espresso/espressopp-1.9.4.1/src/integrator/LatticeBoltzmann.cpp:132:2: 

**warning: #warning : probably one needs to eliminate Ni as input parameter and calculate it through Li and a
/UHOME/nabia.dcy2014/espresso/espressopp-1.9.4.1/src/integrator/LatticeBoltzmann.cpp:190:2: warning: #warning : need to correct zeroMDCMVel if we not at the VERY start of the simulation. It zeros CM Vel EVERY time when integrator.run(X_steps) starts!!!
/UHOME/nabia.dcy2014/espresso/espressopp-1.9.4.1/src/integrator/LatticeBoltzmann.cpp:332:2: warning: #warning : need a foolproof in case there is no access to the integrator (and getTimeStep) yet
/UHOME/nabia.dcy2014/espresso/espressopp-1.9.4.1/src/integrator/LatticeBoltzmann.cpp:697:2: warning: #warning : should one cancel this condition if pure lb is in use? or move setCouplForceLoc into the collision loop?**

[ 70%] Building CXX object src/CMakeFiles/_espressopp.dir/integrator/LatticeSite.cpp.o
[ 70%] Building CXX object src/CMakeFiles/_espressopp.dir/integrator/LiquidGasLB.cpp.o
[ 71%] Building CXX object src/CMakeFiles/_espressopp.dir/integrator/MDIntegrator.cpp.o
and after 97% complet this make step is giving error as-
[ 97%] Building CXX object src/CMakeFiles/_espressopp.dir/storage/bindings.cpp.o

**make[2]: *** No rule to make target `/path/to/library.so', needed by `_espressopp.so'.  Stop.
make[1]: *** [src/CMakeFiles/_espressopp.dir/all] Error 2
make: *** [all] Error 2**

how to fix this issue, what i have to do, can you please help me ? 
thank you

**Comment by junghans** [comment]
> My fftw problem have solved

How has the problem been solved?

> `/path/to/library.so`

This looks like you didn't actually specify where `libfftw` is. `/path/to/library.so` is just meant as an example on how to do it. You have to put your real path and library name there.

**Comment by NABIAHAMAD** [comment]
Hello @junghans, 
As suggested, I tried, but not solved yet.  I have given libfftw path in my .bashrc file as-
#FFTW-3.3.4
export PATH=/UHOME/nabia.dcy2014/FFTW/fftw-3.3.4/bin:$PATH
export LD_LIBRARY_PATH=/UHOM/nabia.dcy2014/FFTW/fftw-3.3.4/libfftw3.la:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/UHOME/nabia.dcy2014/FFTW/fftw-3.3.4/.libs/libfftw3.a:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/UHOME/nabia.dcy2014/FFTW/fftw-3.3.4/.libs/libfftw3.la:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/UHOME/nabia.dcy2014/FFTW/fftw-3.3.4/.libs/libfftw3.lai:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/UHOME/nabia.dcy2014/FFTW/fftw-3.3.4/lib/libfftw3.a:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/UHOME/nabia.dcy2014/FFTW/fftw-3.3.4/lib/libfftw3.la:$LD_LIBRARY_PATH
export CPATH=/UHOME/nabia.dcy2014/FFTW/fftw-3.3.4/include:$CPATH
but the problem remains the same, i am stuck on make step as- 
[ 97%] Building CXX object src/CMakeFiles/_espressopp.dir/storage/Storage.cpp.o
[ 97%] Building CXX object src/CMakeFiles/_espressopp.dir/storage/bindings.cpp.o
**make[2]: *** No rule to make target `/path/to/library.so', needed by `_espressopp.so'.  Stop.
make[1]: *** [src/CMakeFiles/_espressopp.dir/all] Error 2
make: *** [all] Error 2**
Now I am not sure where the "make" is looking for "libfftw". I am trying to install locally espressopp.
Any help on this is highly appreciated.
Thank you

**Comment by junghans** [comment]
`LD_LIBRARY_PATH` is supposed to be the path to the library (without the library file itself) and it makes no sense to be used with static libraries (`.a` files). The `.la` files are coming from libtool, but cmake cannot use them. And `CPATH` is something cmake doesn't use either.

You could try to run cmake with:
```
cmake -DFFTW3_INCLUDES="/UHOME/nabia.dcy2014/FFTW/fftw-3.3.4/include" -DFFTW3_LIBRARIES="/UHOME/nabia.dcy2014/FFTW/fftw-3.3.4/.libs/libfftw3.a"
and then re-make.

**Comment by NABIAHAMAD** [comment]
Thanks @junghans . Now I tried with several fresh install attempts locally. (I do not have root privilage).
If I run first
 cmake . -DEXTERNAL_BOOST=OFF -DEXTERNAL_MPI4PY=OFF
and then
cmake -DFFTW3_INCLUDES="/UHOME/nabia.dcy2014/FFTW/fftw-3.3.4/include" -DFFTW3_LIBRARIES="/UHOME/nabia.dcy2014/FFTW/fftw-3.3.4/.libs/libfftw3.a"
cmake runs with no errors, or else I get errors. But still after that running make I get stuck here:
 
/usr/bin/ld: /UHOME/nabia.dcy2014/python/lib/libpython2.7.a(abstract.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/UHOME/nabia.dcy2014/python/lib/libpython2.7.a: could not read symbols: Bad value
collect2: ld returned 1 exit status
make[2]: *** [_espressopp.so] Error 1
make[1]: *** [src/CMakeFiles/_espressopp.dir/all] Error 2
make: *** [all] Error 2
with the above msg. So am I missing on more libraries? But here please note I installed both "BOOST or MPI4PY libraries". 
Any help/suggestion is highly appreciated.
Thank you

**Comment by junghans** [comment]
Try adding `-DBUILD_SHARED_LIBS=OFF` to one of your `cmake` calls.

**Comment by NABIAHAMAD** [comment]
Thanks @junghans. I could get past the installation without any error message. But in python 
>>> import espressopp
gives the following error msg:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/UHOME/nabia.dcy2014/espresso/espressopp-1.9.4.1/espressopp/__init__.py", line 23, in <module>
    from espressopp.main._setup import *
  File "/UHOME/nabia.dcy2014/espresso/espressopp-1.9.4.1/espressopp/main/_setup.py", line 24, in <module>
    import mpi4py.MPI as MPI
ImportError: /UHOME/nabia.dcy2014/espresso/espressopp-1.9.4.1/contrib/mpi4py/MPI.so: invalid ELF header

Also my installation folder contains the following:
[nabia.dcy2014@hn espressopp-1.9.4.1]$ ls
AUTHORS         CMakeDoxyfile.in            CMakeLists.txt       doc         examples   src
bench           CMakeDoxygenDefaults.cmake  contrib              docker      Makefile   testsuite
cmake           CMakeFiles                  COPYING              ESPRC       NEWS
CMakeCache.txt  cmake_install.cmake         CTestTestfile.cmake  espressopp  README.md
 
further I installed python 2.7 locally before present espresso++ as a previous python 2.6 installation was not working. Well now I am not sure what I am missing, it may be silly, but would appreciate any help/suggestion.

Thank you.

**Comment by MrTheodor** [comment]
This very likely means that you have compiled MPI with the different version of Python that you try to use now.

**Comment by NABIAHAMAD** [comment]
Thanks @MrTheodor. I have installed MPI 3.2 (mpich-3.2.tar.gz) locally, after python2.7.13 installation locally. By the way I didn't get  "install_manifest.txt" in the installation folder /UHOME/nabia.dcy2014/espresso/espressopp-1.9.4.1/
Does it mean something?

**Comment by NABIAHAMAD** [comment]
I do not have this folder:
/UHOME/nabia.dcy2014/python/lib/python2.7/site-packages/espressopp/
So has it something to do for not able to invoke "import espressopp" in python? Any help is appreciated. Plz note I attempted to install espresso++ without root privilage.

**Comment by NABIAHAMAD** [comment]
Just an update: I copied espressopp/ from /UHOME/nabia.dcy2014/espresso/espressopp-1.9.4.1/espressopp  to /UHOME/nabia.dcy2014/python/lib/python2.7/site-packages/espressopp/
but it didn't help. I still can't invoke "import espressopp" in python. Any help is appreciated.

**Comment by NABIAHAMAD** [comment]
Thank you @junghans @MrTheodor for your comments. I did fresh install of cmake-3.9.3, boost_1_64_0, mpich-3.2, and fftw-3.3.4. Since this installations were done locally so I installed them in following folders:
/UHOME/nabia.dcy2014/cmake-3.9/cmake-3.9.3/
/UHOME/nabia.dcy2014/boost/boost_1_64_0/
/UHOME/nabia.dcy2014/MPI/
/UHOME/nabia.dcy2014/FFTW/fftw-3.3.4/

Now after all this I reinstalled espressopp with cmake commands 

cmake . -DEXTERNAL_BOOST=OFF  -DBUILD_SHARED_LIBS=OFF
and
cmake -DFFTW3_INCLUDES="/UHOME/nabia.dcy2014/FFTW/fftw-3.3.4/include" -DFFTW3_LIBRARIES="/UHOME/nabia.dcy2014/FFTW/fftw-3.3.4/.libs/libfftw3.a"

Files _espressopp.so and install_manifest.txt  are still missing from the installation folder /UHOME/nabia.dcy2014/espresso/espressopp-1.9.4.1/
Also espresopp/ is missing in UHOME/nabia.dcy2014/python/lib/python2.7/site-packages/
So I produced symbolic links of  _espressopp.so in the installation folder and of espressopp/ in site-packages.
Now this is the error msg that I get on invoking 
>>> import espressopp

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "espressopp/__init__.py", line 23, in <module>
    from espressopp.main._setup import *
  File "espressopp/main/_setup.py", line 26, in <module>
    import _espressopp
ImportError: ./_espressopp.so: invalid ELF header

I am pretty naive to all this, kindly help. I am stuck without any clue. I await a reply.

Thanks.

**Comment by junghans** [comment]
@NABIAHAMAD, please try to build fftw with `--enable-shared` and then try:
```
cmake  -DEXTERNAL_BOOST=OFF  -DBUILD_SHARED_LIBS=ON -DFFTW3_INCLUDES="/UHOME/nabia.dcy2014/FFTW/fftw-3.3.4/include" -DFFTW3_LIBRARIES="/UHOME/nabia.dcy2014/FFTW/fftw-3.3.4/.libs/libfftw3.so"
```
If I remember correctly python modules need to shared objects.

**Comment by NABIAHAMAD** [comment]
Thanks @junghans and also @MrTheodor. import espressopp in python ran with no errors. I built python and fftw with --enable-shared and then tried: 
cmake  -DEXTERNAL_BOOST=OFF -DEXTERNAL_MPI4PY=OFF -DBUILD_SHARED_LIBS=ON -DFFTW3_INCLUDES="/UHOME/nabia.dcy2014/FFTW/fftw-3.3.4/include" -DFFTW3_LIBRARIES="/UHOME/nabia.dcy2014/FFTW/fftw-3.3.4/.libs/libfftw3.so"
