### ISSUE TITLE
Espressopp Mac OS installation issue

### ISSUE THREAD

**Issue by Nickluas** [espressopp/espressopp#200]
Hi, I'm new to the espressopp and having some troubles to build it on my mac, can anyone help me out?
I installed all the required libraries, then followed the quick installation instructions using cmake, it gave some warnings as below:

```
>>>cmake -DEXTERNAL_BOOST=OFF -DEXTERNAL_MPI4PY=OFF .
-- PYTHON_INCLUDE_PATH = /Users/mbcx/anaconda2/include/python2.7
-- PYTHON_VERSION = 2.7
-- PYTHON_LIBDIR = /Users/mbcx/anaconda2/lib
-- PYTHON_LIBRARIES = /usr/lib/libpython2.7.dylib
-- Generate system documentation via /usr/local/bin/doxygen: make doc
-- Generate user documentation via /Users/mbcx/anaconda2/bin/sphinx-build: make ug
-- Generate LaTeX manual via /Users/mbcx/anaconda2/bin/sphinx-build: make ug-pdf
-- Configuring done
CMake Warning (dev):
  Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
  --help-policy CMP0042" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

MACOSX_RPATH is not specified for the following targets:

   MPI
   _espressopp
   dl
This warning is for project developers.  Use -Wno-dev to suppress it.
-- Generating done
-- Build files have been written to: /Users/mbcx/Research/espressopp-1.9.4.1
```

If I ignore the warning and do the make, I got some warnings during the make:

```
/User/mbcx/espressopp-1.9.4.1/contrib/boost/boost/mpl/print.hpp:50:19: warning: 
      in-class initialization of non-static data member is a C++11 extension
      [-Wc++11-extensions]
    const int m_x = 1 / (sizeof(T) - sizeof(T));
```

but there are no other errors appear after finish making. but I got a segmentation fault error when I tried to import the espressopp in python

```
>>>python
Python 2.7.13 |Anaconda 4.3.1 (x86_64)| (default, Dec 20 2016, 23:05:08) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>>import espressopp
>>>Segmentation fault: 11
```

Thanks
Le

**Comment by junghans** [comment]
Hmm, try to buid with it with `-DCMAKE_BUILD_TYPE=Debug` and run it in `gdb`.

**Comment by niktre** [comment]
@Nickluas the warning in `cmake` shouldn't affect `make` (theoretically). This warning can be suppressed by adding `set(CMAKE_MACOSX_RPATH 1)` into `CMakeLists.txt` ([https://stackoverflow.com/questions/31561309/cmake-warnings-under-os-x-macosx-rpath-is-not-specified-for-the-following-targe#31567991](found here)). 

The warning about c++11 initialization comes from the fact that not the whole code of ESPResSo++ is C++11 conform, but we are working on it. Such warnings do NOT affect the building process.

My tip is that the segmentation fault comes from the incompatibility of Anaconda python and system's python. Your dynamic python library (`PYTHON_LIBRARIES`) seems to refer to the system's python, but all the rest to the one from anaconda.

Could you try to switch anaconda's python off and recompile from scratch in such a way that `PYTHON_INCLUDE_PATH` and `PYTHON_LIBDIR` are referring to the system's python?

**Comment by Nickluas** [comment]
@niktre Thanks so much! You are right, it works perfectly after I disable the Anaconda!
