### ISSUE TITLE
Compilation with clang 

### ISSUE THREAD

**Issue by niktre** [espressopp/espressopp#204]
Hi! For a long time there have been a lot of warnings during compilation of E++ on Mac about non-static data members of `boost`:
```
myFork_espressopp/contrib/boost/boost/mpl/print.hpp:50:19: warning: in-class initialization of non-static data member is a C++11
      extension [-Wc++11-extensions]
    const int m_x = 1 / (sizeof(T) - sizeof(T));
```

These warnings can be overcome by running `cmake` with `-DCMAKE_CXX_FLAGS=-std=c++11` (or, equivalently, modifying the Makefile correspondingly). 

Do you think we have to incorporate this flag into Makefile on a permanent basis? Is simplifies the compilation process significantly especially when one has to look for some particular error or warning.

**Comment by junghans** [comment]
I thought we enable C++11 always for all compiler here: https://github.com/espressopp/espressopp/blob/master/CMakeLists.txt#L22 ?

@MrTheodor do you know?

**Comment by MrTheodor** [comment]
But then why the requirement for CMake version is not checked ?

**Comment by niktre** [comment]
@MrTheodor Sorry, I didn't formulate it clear. I had to change the requirement for the minimal `CMake` version in `CMakeLists.txt` (from 3.1 to 2.8) to make E++ compile. Since the requirement `CMAKE_CXX_STANDARD` works starting with `CMake 3.1` it didn't work in my case and I got all the warnings. 

The question is what is the standard `CMake` on Apple devices. I'll check it and post it here.

**Comment by junghans** [comment]
Ok, so the conclusion here is that @niktre modified `CMakeLists.txt` and as consequence of that found the above issue?

Recent versions of CMake for OSX can be found here https://cmake.org/download/, it literally takes 30secs to install one. 

So I marked this issue as invalid.
