### ISSUE TITLE
Instrumenting ESPResSo++ with score-p

### ISSUE THREAD

**Issue by ocaisa** [espressopp/espressopp#205]
I wanted to do some performance analysis on ESPResSo++ and I instrumented it with Score-P. The execution model of E++ is one I like and I wanted to see how well that is supported by common performance analysis tools. The instrumentation went fine but I ran into a few problems trying to collect a measurement (there are some details in https://github.com/score-p/scorep_binding_python/issues/1 ).

The specific problem is 
```
[Score-P] src/measurement/profiling/scorep_profile_event_base.c:187: Error: Inconsistent profile. Stop profiling: Exit event for other than current region occurred at location 0: Expected exit for region espressopp::CellGrid::CellGrid. Exited region espressopp.pmi:__call__
```
and happens with more than 8 cores. It seems to come from
https://github.com/espressopp/espressopp/blob/master/examples/lennard_jones/lennard_jones.py#L259
since if I comment out this step I get a successful meaurement. I was wondering if perhaps you knew offhand what the problem might be and, if not, what is the implication of commenting out this line (i.e., does the experiment still make sense)?

**Comment by XzzX** [comment]
Reopen if problem still persists.
