### ISSUE TITLE
TDforce: problems with compilation

### ISSUE THREAD

**Issue by niktre** [espressopp/espressopp#211]
I encountered problems with compilation of `TDforce.hpp`
The problem seems to be with the switch from `map` to `unordered_map`.

In Garching, I use external boost 1.61 and intel compiler v. 16

The error I get is:
`
In file included from /usr/include/c++/4.3/unordered_map(40),
                 from /u/nikt/jan_2tlb/src/integrator/TDforce.hpp(35),
                 from /u/nikt/jan_2tlb/src/integrator/bindings.cpp(29):
/usr/include/c++/4.3/c++0x_warning.h(36): error: #error directive: This file requires compiler and library support for the upcoming ISO C++ standard, C++0x. This support is currently experimental, and must be enabled with the -std=c++0x or -std=gnu++0x compiler options.
`

If I compile with the flag ´-std=c++0x´, I get another error:
`
/u/system/SLES11/soft/boost/1.61/intel-16.0/impi-5.1.3/include/boost/serialization/map.hpp(65): error: class "std::map<size_t={unsigned long}, espressopp::analysis::sBuf, std::less<size_t={unsigned long}>, std::allocator<std::pair<const size_t={unsigned long}, espressopp::analysis::sBuf>>>" has no member "emplace_hint"
                  s.emplace_hint(hint, t.reference());
`

Switching back to `map` solves the problem. Any thoughts how can I make `unordered_map` work?

**Comment by junghans** [comment]
In your first error you are using gcc-4.3 headers, which are ancient. The intel compiler depends on gcc headers, so make sure you have a recent gcc loaded ,too.

**Comment by MrTheodor** [comment]
@niktre can we close it?

**Comment by junghans** [comment]
ping @niktre

**Comment by XzzX** [comment]
Reopen if problem still persists.
