### ISSUE TITLE
Pressure difference between espressopp and gromacs

### ISSUE THREAD

**Issue by mehmetsayar** [espressopp/espressopp#217]
Hi,

I am trying to import a system from gromacs to espressopp.
The system is a simple LJ system. Two types of particles A and B.  No bonds, no angles, etc.
I compare the two packages by doing a 0 step integration (gmx mdrun -nsteps 0), just to calculate the energy and pressure of the current configuration. 

When I check the potential and kinetic energy everything seems to be fine, I get the same energy up to 4 digits from both gromacs and espressopp.

However, when I compare the pressure values the pressure I get from gromacs is much higher (88.1207) compared to the espressopp value (4.835). 

I compared the forces. The accuracy is not as good as the energy, but seems to be OK upto 2 digits or so. 

Any ideas?
Thank you,

Mehmet
[test.zip](https://github.com/espressopp/espressopp/files/1924579/test.zip)

**Comment by mehmetsayar** [comment]
I used espressopp-1.9.5 and gromacs 5.1.5
test.zip file includes all gromacs and espressopp files to test the system output.

**Comment by junghans** [comment]
@mehmetsayar: I remember there was some kind of issue in gromacs-5.1, I would start by using a more recent version of gromacs, e.g. gromacs-2018.1!

**Comment by mehmetsayar** [comment]
Thanks Christoph.

I tried it with 2018.1. Exactly the same result.

**Comment by mehmetsayar** [comment]
Hi all,
Many thanks to Karsten Kreis, the problem is resolved.  I attached his explanation for the pressure difference between Gromacs and Espressopp below. Basically there is a conversion factor related to atomic mass units which are used in Gromacs. 

So I am closing this issue.
All the best,

Mehmet

Karsten's message:

Gromacs outputs pressure in bar, while esprossopp outputs pressure in internal MD units based on whatever you put in for you potential energy, etc. And if you use the same units like gromacs for your input - what we usually do, as far as I know - then your pressure output does not correspond to bar. And in fact, converting the output into bar units does require an additional conversion factor, which happens to be 16.6. Therefore, this factor 16.6 sounds very familiar to me.

This is explained also in the gromacs manual, see here (section 2.2 MD units, caption of table 2.2): http://manual.gromacs.org/documentation/current/manual-2018.1.pdf
In this old, old answer on the gromacs user email list, one of the gromacs developers also refers to this factor: http://gromacs.org_gmx-users.maillist.sys.kth.narkive.com/shKj2sqT/pressure-calculation

I hope that solves the problem! :)

Best,
Karsten

**Comment by kkreis** [comment]
Cheers! Yeah, I had to do this conversion several times myself :)
