### ISSUE TITLE
Parallel run 

### ISSUE THREAD

**Issue by eduardodinizRO** [espressopp/espressopp#223]
Hello everyone,
I know this is probably a naive question, but when I run the espressopp python script from the fadress_protein folder in the examples directory, the run is not using all cores. The command I'm using is python ubiquitin.py. Is this the correct command for a parallel run? Thank you for any help

**Comment by govarguz** [comment]
@eduardodinizRO 
try using  >mpirun -n $nrOfCores python ubiquitin.py
with $nrOfCores =4, 8 or the number of available cores you may have

**Comment by eduardodinizRO** [comment]
It worked!! Thank you!
