### ISSUE TITLE
Move to Python3

### ISSUE THREAD

**Issue by junghans** [espressopp/espressopp#227]
https://pythonclock.org/

**Comment by jkrajniak** [comment]
Question regarding this task (rather decision for product owner); do we plan to still support Python 2.x if we migrate the code base to Python 3.x ?

**Comment by junghans** [comment]
Fedora 30 doesn't include h5py (and other packages) for python2 anyhow, so we have to start moving on this!

**Comment by stuehn** [comment]
Supporting python2 and python3 at the same time would in principle be possible. But due to limited manpower I would opt to drop python2 support completely. Since moving to python3 will render many existing espressopp scripts non-working we have to provide some kind of upgrade path for old user-scripts as well. ESPResSo++ 3.0 would be a nice version number for python3 support ;-)

**Comment by junghans** [comment]
`2to3` with a bunch to tweaks?

**Comment by jkrajniak** [comment]
I suppose, on branch `py3` I have already done the basic conversion with `2to3`. It compiles, however there is an issue with abstract classes which are not compatible with py3. Also, I am not entirely sure that PMI itself can work with py3.

**Comment by junghans** [comment]
@olenz do you have a PMI for python3?

**Comment by mcepl** [comment]
> `2to3` with a bunch to tweaks?

It is a way not enough: as a person who ported another large project (with C extensions; [M2Crypto](https://gitlab.com/m2crypto/m2crypto/)) to be dual py2k/py3k, I can tell you that ``2to3`` just doesn't even start to cover what’s the most complicated: dealing with different versions of strings.

Some documentation on the topc:
* https://docs.python.org/3/howto/pyporting.html and https://docs.python.org/3/howto/cporting.html are pretty good introduction
* https://matej.ceplovi.cz/clanky/PyCon18-m2crypto/ presentation I had on the topic on PyConCZ'18
* http://python-future.org/compatible_idioms.html is pretty nice as well

**Comment by junghans** [comment]
Time is nearly up....

**Comment by junghans** [comment]
And the time is up!

**Comment by junghans** [comment]
https://bugs.gentoo.org/713568

**Comment by junghans** [comment]
https://github.com/gentoo/gentoo/commit/3f27a5538a39a015c40986c25baf86d12dae1582
