### ISSUE TITLE
dump_xtc installation error

### ISSUE THREAD

**Issue by oestrika** [espressopp/espressopp#233]
Hi everbody,
I tried to install the .xtc extension in a Docker Container (Ubuntu 17.10 and 18.04) with GROMACS not installed in standard directory (i.d. not using apt-get). Every time running the installation with

cmake -DWITH_XTC=ON -DGROMACS_LIBRARIES=${gromacs_prefix}/lib/-DGROMACS_INCLUDES=${gromacs_prefix}/include .

I received following error message:

[ 93%] Building CXX object src/CMakeFiles/_espressopp.dir/io/bindings.cpp.o
In file included from /Downloads/espressopp-1.9.5/src/io/DumpXTC.cpp:23:0:
/Downloads/espressopp-1.9.5/src/io/DumpXTC.hpp:40:10: fatal error: gromacs/fileio/xtcio.h: No such file or directory
 #include "gromacs/fileio/xtcio.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
src/CMakeFiles/_espressopp.dir/build.make:4646: recipe for target 'src/CMakeFiles/_espressopp.dir/io/DumpXTC.cpp.o' failed
make[2]: *** [src/CMakeFiles/_espressopp.dir/io/DumpXTC.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /Downloads/espressopp-1.9.5/src/io/bindings.cpp:32:0:
/Downloads/espressopp-1.9.5/src/io/DumpXTC.hpp:40:10: fatal error: gromacs/fileio/xtcio.h: No such file or directory
 #include "gromacs/fileio/xtcio.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
src/CMakeFiles/_espressopp.dir/build.make:4694: recipe for target 'src/CMakeFiles/_espressopp.dir/io/bindings.cpp.o' failed
make[2]: *** [src/CMakeFiles/_espressopp.dir/io/bindings.cpp.o] Error 1

When using ap-get everthing wokes fine. I also copied the GROMACS include directory (non standard path) to /usr/include and that also worked. 
But sinsce I would like to run simulations on an HPC cluster (Centos 7.2) this workaround is not possible.

Best Marco

**Comment by junghans** [comment]
Can you try that patch in #234?

**Comment by oestrika** [comment]
Yes, it works. Thanks a lot.

Best Marco

**Comment by oestrika** [comment]
I'm very sorry I forgot to check wheter it is running correctly after installation. So now I have this error:

# python -c 'import espressopp'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Apps/espressopp/lib/python2.7/dist-packages/espressopp/__init__.py", line 23, in <module>
    from espressopp.main._setup import *
  File "/Apps/espressopp/lib/python2.7/dist-packages/espressopp/main/_setup.py", line 26, in <module>
    import _espressopp
ImportError: /Apps/espressopp/lib/python2.7/dist-packages/_espressopp.so: undefined symbol: write_xtc

It seems installation failed without error message.

**Comment by junghans** [comment]
Can you do an:
```
ldd /Apps/espressopp/lib/python2.7/dist-packages/_espressopp.so
```

**Comment by junghans** [comment]
I think your `-DGROMACS_LIBRARIES=${gromacs_prefix}/lib` is wrong! `-DGROMACS_LIBRARIES` needs to point to the library (e.g. `libgromacs.so`) itself and not the library path.

**Comment by oestrika** [comment]
$ ldd /Apps/espressopp/lib/python2.7/dist-packages/_espressopp.so
	linux-vdso.so.1 (0x00007ffdbe58a000)
	libboost_mpi.so.1.65.1 => /usr/lib/x86_64-linux-gnu/libboost_mpi.so.1.65.1 (0x00007f8ca6304000)
	libboost_python-py27.so.1.65.1 => /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.65.1 (0x00007f8ca60c4000)
	libboost_serialization.so.1.65.1 => /usr/lib/x86_64-linux-gnu/libboost_serialization.so.1.65.1 (0x00007f8ca5e86000)
	libboost_system.so.1.65.1 => /usr/lib/x86_64-linux-gnu/libboost_system.so.1.65.1 (0x00007f8ca5c81000)
	libboost_filesystem.so.1.65.1 => /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.65.1 (0x00007f8ca5a67000)
	libpython2.7.so.1.0 => /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0 (0x00007f8ca54ea000)
	libmpi_cxx.so.20 => /usr/lib/x86_64-linux-gnu/libmpi_cxx.so.20 (0x00007f8ca52d0000)
	libmpi.so.20 => /usr/lib/x86_64-linux-gnu/libmpi.so.20 (0x00007f8ca4fde000)
	libfftw3.so.3 => /usr/lib/x86_64-linux-gnu/libfftw3.so.3 (0x00007f8ca4bdc000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f8ca484e000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f8ca44b0000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f8ca4298000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f8ca3ea7000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f8ca3c88000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f8ca3a6b000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f8ca3867000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f8ca3664000)
	libopen-rte.so.20 => /usr/lib/x86_64-linux-gnu/libopen-rte.so.20 (0x00007f8ca33dc000)
	libopen-pal.so.20 => /usr/lib/x86_64-linux-gnu/libopen-pal.so.20 (0x00007f8ca312a000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f8ca2f22000)
	libhwloc.so.5 => /usr/lib/x86_64-linux-gnu/libhwloc.so.5 (0x00007f8ca2ce5000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f8ca793f000)
	libnuma.so.1 => /usr/lib/x86_64-linux-gnu/libnuma.so.1 (0x00007f8ca2ada000)
	libltdl.so.7 => /usr/lib/x86_64-linux-gnu/libltdl.so.7 (0x00007f8ca28d0000)

**Comment by oestrika** [comment]
yes, using 
-DGROMACS_LIBRARIES=${gromacs_prefix}/lib/libgromacs.so 
worked. Thanks
