### ISSUE TITLE
Unique potentials

### ISSUE THREAD

**Issue by niktre** [espressopp/espressopp#245]
Does anybody know what purpose do all Unique potentials serve? Are they there for pressure tensor calculation?
I mean:
```
AngularUniqueCosineSquared
AngularUniqueHarmonic
AngularUniquePotential
CoulombTruncatedUniqueCharge
DihedralHarmonicUniqueCos
DihedralUniquePotential
HarmonicUnique
PotentialUniqueDist
```
**And most important question:** does anybody use them or rely on them?

**Comment by niktre** [comment]
@vitst can you still remember what are they for?

**Comment by junghans** [comment]
ping @vitst

**Comment by vitst** [comment]
@niktre Oh my, I totally missed the question. I can't recall I ever used these potentials at all. I don't know what is specific about them.
