### ISSUE TITLE
AttributeError: 'h5py.h5p.PropFAID' object has no attribute 'set_fapl_mpio'

### ISSUE THREAD

**Issue by junghans** [espressopp/espressopp#250]
All the CI is broken with the following error:
```
AttributeError: 'h5py.h5p.PropFAID' object has no attribute 'set_fapl_mpio'
```
details here:https://travis-ci.org/espressopp/espressopp/jobs/472171056

**Comment by junghans** [comment]
cc'ing @niktre as he did the last merge!

**Comment by pdebuyl** [comment]
For info, this is typically what you get if either HDF5 or h5py are built without MPI support.

**Comment by junghans** [comment]
It seems on Fedora, at least, h5py isn't build with mpi support, see: https://src.fedoraproject.org/rpms/h5py/blob/master/f/h5py.spec

**Comment by jkrajniak** [comment]
Only the tests regarding `h5md` are broken.
For Ubuntu, the h5py from package `python-h5py` works correctly - in constrast to `pip` version.
I am working on the solution;

**Comment by fedepad** [comment]
@jkrajniak Can you point to the line of code where h5py is installed? 
I don't find it with a simple search in the repository. 

Making sure that HDF5 was installed in parallel mode, I would pull the source stable of a specific (if needed) h5py version and directly configure:
```
$ export CC=mpicc
$ python setup.py configure --mpi [--hdf5=/path/to/parallel/hdf5]
$ python setup.py build
```
this is just one way. 
Another way with env variables...these methods I used and are ok. 
We should follow the following doc basically and include the few lines in one of the two ways:
http://docs.h5py.org/en/stable/build.html#custom-installation
Finding the path to the parallel HDF5 installed by package manager should be easy.

**Comment by junghans** [comment]
It gets installed here: https://github.com/espressopp/buildenv/blob/master/fedora#L12

**Comment by jkrajniak** [comment]
Very likely using distribution packages instead of pip could solve the problem;

**Comment by junghans** [comment]
Can you do a PR in buidenv?

**Comment by fedepad** [comment]
@jkrajniak Which version of HDF5 is required for pyh5md? Has to be 1.8.x versions or it supports 1.10 too?

**Comment by chrisspen** [comment]
Was there any fix for this in the Pip version? I still get this error.
