### ISSUE TITLE
Holding a process during file /IO: A bug in analysis::ConfigurationsExt::gater()?

### ISSUE THREAD

**Issue by eleep** [espressopp/espressopp#252]
Hello,
I'm Dr. Eunsang Lee working in Halle Univ. 
I'm using espresso++ for my project in the JUWELS cluster of JSC.
I got a problem that the simulation holds without any message. 
I found that it is from DumpGRO(), DumpXTC(), and DumpXYZ() classes which all include analysis::ConfigurationsExt::gather().
In this function, slave processors send an empty message to the master processor, but there's a mismatch of comm->irecv() in slave processors and comm->send() in the master processor.(three comm->send() from the master but only two comm->irecv() in slaves.)
I deleted the last comm->send() at a line 236 of analysis/ConfigurationsExt.cpp which seems to be unnecessary, and the problem has been solved.
I don't completely understand the algorithm of this class, but It's strange that I haven't had such a problem with the original code in other clusters.
So I would like to ask you whether it's really a bug or whether I have misunderstood something.
Thank you for the great simulation package and your effort on it.
Eunsang.

**Comment by GDeichmann** [comment]
Hello Eunsang,
At the moment I am not sure where the problem is but I will try to have a look at it.
From my understanding this part of the code serves to check all nodes for consistency in the number of coords, velocs and ids, so normally (I guess) the simulation should run fine without it.
Could you provide a minimum example that reproduces the error?

**Comment by jkrajniak** [comment]
Maybe the issue is due to the fact that some of the processes have 0 particles (e.g. diluted system)? I remember that for DumpGRO there was such weird case.

**Comment by eleep** [comment]
Dear all,
here's an example of the "analysis::ConfigurationsExt.cpp" I modified.
As far as I understood, the master receives the number of particles in each processor, their coordinates and velocities from slaves (at lines 217, 222, 235 for receiving and at lines 294, 299, 300 for sending). 
Before each stage, the master sends an empty message to the slaves (at lines 218, 223, 236 for sending and 294, 297 for receiving). 
Here, there are three sending functions in the master but only two receiving in slaves.
Two methods have solved the problems of the holding process. 
First, I deleted the line 236, or second, I added a function of receiving an empty message before sending velocities between lines 299 and 300.(289// and 299//)

Actually, my system is polymers in melt density, so there's no chance of 0 particles in a processor.
Thank you.
Eunsang.

---

122     void ConfigurationsExt::gather() {
...
195       if (system.comm->rank() == 0) {
...
207            if (iproc) {
...
217               req = system.comm->irecv<int>(iproc, DEFAULT_TAG, ids, maxN);
218               system.comm->send(iproc, DEFAULT_TAG, 0);
219               stat = req.wait();
220               nIds = *stat.count<int>();
221 
222               req = system.comm->irecv<real>(iproc, DEFAULT_TAG, coordinates, 3*maxN);
223               system.comm->send(iproc, DEFAULT_TAG, 0);
224               stat = req.wait();
225               nCoords = *stat.count<real>();
...
235               req = system.comm->irecv<real>(iproc, DEFAULT_TAG, velocities, 3*maxN);
236 //              system.comm->send(iproc, DEFAULT_TAG, 0);
237               stat = req.wait();
238               nVelocs = *stat.count<real>();
...
249            } else {
250              nother = myN;
251            }
...
280        } else {
...
289        boost::mpi::request requests[2];
289//      boost::mpi::request requests[3];
290        boost::mpi::status stat;
...
294        requests[0] = system.comm->irecv<int>(0, DEFAULT_TAG, tmp);
295        system.comm->send<int>(0, DEFAULT_TAG, ids, myN);
296        stat = requests[0].wait();
297        requests[1] = system.comm->irecv<int>(0, DEFAULT_TAG, tmp);
298        stat = requests[1].wait();
299        system.comm->send<real>(0, DEFAULT_TAG, coordinates, 3*myN);
299//      requests[2] = system.comm->irecv<int>(0, DEFAULT_TAG, tmp);
299//      stat = requests[2].wait();
300        system.comm->send<real>(0, DEFAULT_TAG, velocities, 3*myN);
301       }
...
310    }

**Comment by XzzX** [comment]
Reopen if problem still persists.
