### ISSUE TITLE
Could not find the following Boost libraries: boost_python with boost-1.69 and cmake-3.14

### ISSUE THREAD

**Issue by junghans** [espressopp/espressopp#277]
With cmake-3.14 and python-1.69, I got:
```
CMake Error at /opt/cmake-3.14.0/share/cmake-3.14/Modules/FindBoost.cmake:2132 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.69.0

  Boost include path:
  /opt//boost-1.69.0/include


  Could not find the following Boost libraries:

          boost_python

  Some (but not all) of the required Boost libraries were found.  You may
  need to install these additional Boost libraries.  Alternatively, set
  BOOST_LIBRARYDIR to the directory containing Boost libraries or BOOST_ROOT
  to the location of Boost.
```

The core of the issue can be found in `FindBoost.cmake`:

> Note that Boost Python components require a Python version suffix
> (Boost 1.67 and later), e.g. ``python36`` or ``python27`` for the
> versions built against Python 3.6 and 2.7, respectively.

This basically means for Boost-1.67 and later, we need to check for the `python27` component instead of just `python`, however this feature is only supported in cmake-3.11 and newer.

**Comment by henkela** [comment]
In case it's helpful. Just patched the CMakeLists.txt to check for python27 using CMake 3.13.4, which found the lib successfully.

**Comment by junghans** [comment]
Yeah, that would be the ultimate solution when all system had boost-1.67 or higher.
