### ISSUE TITLE
Missing boost/align header files

### ISSUE THREAD

**Issue by jnvance** [espressopp/espressopp#298]
There are some missing header files in boost/align that are needed for defining `AlignedVector` used in the vectorization submodule. Not sure how this wasn't detected by Travis-CI (maybe with EXTERNAL_BOOST=OFF compilation still includes the header files from libboost-all-dev in the docker image).

**Comment by jkrajniak** [comment]
It's weird as both are tested, EXTERNAL_BOOST=OFF/ON
