### ISSUE TITLE
Cmake error on MPI

### ISSUE THREAD

**Issue by marianoimperatore** [espressopp/espressopp#300]
Hi, I get the below error when I run the cmake . command from within the git hub cloned version of espresso++ on ubuntu 18.04. Log error file is also reported afterwards.
There's something wrong with my MPI settings I believe, but I have no idea and struggling track back in cmake what's wrong. All mpi fortran libs and compilers should be there.
Please help! Thank you very much!

mariano@mariano-HP-Pavilion-15-Notebook-PC:~/Programs/espressopp$ cmake .
-- Could NOT find MPI_CXX (missing: MPI_CXX_WORKS) 
CMake Error at /home/mariano/cmake-3.17.0-Linux-x86_64/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
  Could NOT find MPI (missing: MPI_CXX_FOUND) (found version "3.1")

      Reason given by package: MPI component 'Fortran' was requested, but language Fortran is not enabled.  

Call Stack (most recent call first):
  /home/mariano/cmake-3.17.0-Linux-x86_64/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:445 (_FPHSA_FAILURE_MESSAGE)
  /home/mariano/cmake-3.17.0-Linux-x86_64/share/cmake-3.17/Modules/FindMPI.cmake:1717 (find_package_handle_standard_args)
  CMakeLists.txt:70 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/mariano/Programs/espressopp/CMakeFiles/CMakeError.log".

--------------------------------------------------------------------------------
**Error log file** 

The MPI test test_mpi for CXX in mode normal failed to compile with the following output:
Change Dir: /home/mariano/Programs/espressopp/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make cmTC_14f96/fast && /usr/bin/make -f CMakeFiles/cmTC_14f96.dir/build.make CMakeFiles/cmTC_14f96.dir/build
make[1]: Entering directory '/home/mariano/Programs/espressopp/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_14f96.dir/test_mpi.cpp.o
/usr/bin/c++   -isystem /usr/lib/x86_64-linux-gnu/openmpi/include/openmpi -isystem /usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/opal/mca/event/libevent2022/libevent -isystem /usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/opal/mca/event/libevent2022/libevent/include -isystem /usr/lib/x86_64-linux-gnu/openmpi/include -isystem /usr/include/mpich  -pthread -std=c++11 -o CMakeFiles/cmTC_14f96.dir/test_mpi.cpp.o -c /home/mariano/Programs/espressopp/CMakeFiles/FindMPI/test_mpi.cpp
Linking CXX executable cmTC_14f96
/home/mariano/cmake-3.17.0-Linux-x86_64/bin/cmake -E cmake_link_script CMakeFiles/cmTC_14f96.dir/link.txt --verbose=1
/usr/bin/c++       -Wl,-Bsymbolic-functions -Wl,-z,relro CMakeFiles/cmTC_14f96.dir/test_mpi.cpp.o  -o cmTC_14f96  /usr/lib/x86_64-linux-gnu/libmpichcxx.so /usr/lib/x86_64-linux-gnu/libmpich.so 
CMakeFiles/cmTC_14f96.dir/test_mpi.cpp.o: In function `MPI::Intracomm::Intracomm()':
test_mpi.cpp:(.text._ZN3MPI9IntracommC2Ev[_ZN3MPI9IntracommC5Ev]+0x14): undefined reference to `MPI::Comm::Comm()'
CMakeFiles/cmTC_14f96.dir/test_mpi.cpp.o: In function `MPI::Intracomm::Intracomm(ompi_communicator_t*)':
test_mpi.cpp:(.text._ZN3MPI9IntracommC2EP19ompi_communicator_t[_ZN3MPI9IntracommC5EP19ompi_communicator_t]+0x28): undefined reference to `MPI::Comm::Comm()'
test_mpi.cpp:(.text._ZN3MPI9IntracommC2EP19ompi_communicator_t[_ZN3MPI9IntracommC5EP19ompi_communicator_t]+0x4d): undefined reference to `ompi_mpi_comm_null'
test_mpi.cpp:(.text._ZN3MPI9IntracommC2EP19ompi_communicator_t[_ZN3MPI9IntracommC5EP19ompi_communicator_t]+0x88): undefined reference to `ompi_mpi_comm_null'
CMakeFiles/cmTC_14f96.dir/test_mpi.cpp.o: In function `MPI::Cartcomm::Cartcomm(ompi_communicator_t* const&)':
test_mpi.cpp:(.text._ZN3MPI8CartcommC2ERKP19ompi_communicator_t[_ZN3MPI8CartcommC5ERKP19ompi_communicator_t]+0x54): undefined reference to `ompi_mpi_comm_null'
test_mpi.cpp:(.text._ZN3MPI8CartcommC2ERKP19ompi_communicator_t[_ZN3MPI8CartcommC5ERKP19ompi_communicator_t]+0xa3): undefined reference to `ompi_mpi_comm_null'
CMakeFiles/cmTC_14f96.dir/test_mpi.cpp.o: In function `MPI::Graphcomm::Graphcomm(ompi_communicator_t* const&)':
test_mpi.cpp:(.text._ZN3MPI9GraphcommC2ERKP19ompi_communicator_t[_ZN3MPI9GraphcommC5ERKP19ompi_communicator_t]+0x54): undefined reference to `ompi_mpi_comm_null'
CMakeFiles/cmTC_14f96.dir/test_mpi.cpp.o:test_mpi.cpp:(.text._ZN3MPI9GraphcommC2ERKP19ompi_communicator_t[_ZN3MPI9GraphcommC5ERKP19ompi_communicator_t]+0xa3): more undefined references to `ompi_mpi_comm_null' follow
CMakeFiles/cmTC_14f96.dir/test_mpi.cpp.o: In function `MPI::Op::Init(void (*)(void const*, void*, int, MPI::Datatype const&), bool)':
test_mpi.cpp:(.text._ZN3MPI2Op4InitEPFvPKvPviRKNS_8DatatypeEEb[_ZN3MPI2Op4InitEPFvPKvPviRKNS_8DatatypeEEb]+0x26): undefined reference to `ompi_mpi_cxx_op_intercept'
test_mpi.cpp:(.text._ZN3MPI2Op4InitEPFvPKvPviRKNS_8DatatypeEEb[_ZN3MPI2Op4InitEPFvPKvPviRKNS_8DatatypeEEb]+0x45): undefined reference to `ompi_op_set_cxx_callback'
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_14f96.dir/build.make:105: recipe for target 'cmTC_14f96' failed
make[1]: *** [cmTC_14f96] Error 1
make[1]: Leaving directory '/home/mariano/Programs/espressopp/CMakeFiles/CMakeTmp'
Makefile:138: recipe for target 'cmTC_14f96/fast' failed
make: *** [cmTC_14f96/fast] Error 2

**Comment by jnvance** [comment]
Hi! it looks like you have both OpenMPI and MPICH installed. While test_mpi.cpp.o is built with OpenMPI included first, the executable cmTC_14f96 is being linked to only the mpich library. Try to check whether this is the case, and maybe uninstall one or the other.

**Comment by junghans** [comment]
@jnvance why are we requiring the Fortran component?

**Comment by jnvance** [comment]
> @jnvance why are we requiring the Fortran component?

That seems to come from CMake's [FindMPI Module](https://github.com/Kitware/CMake/blob/ff4388e90bf65423123638f65640a2b3dcabfbb6/Modules/FindMPI.cmake#L1409). Not sure why missing MPI_CXX_FOUND is the error thrown but the message talks about Fortran.

**Comment by junghans** [comment]
I usually used Spack to install espresso++:
```
git clone https://github.com/spack/spack.git
. spack/share/spack/setup-env.sh
spack install -v py-espressopp@develop ^py-numpy@1.16.6
```

**Comment by fedepad** [comment]
@jnvance Among other errors, FindMPI show what @junghans was pointing out: Fortran is not enabled as a language but is requested by the FindMPI module. If not necessary, one could request to FindMPI only the components that are needed and not all of them. Right now:
https://github.com/espressopp/espressopp/blob/43b72f85395b99781ca7d80eef91c56c7f761258/CMakeLists.txt#L70

doesn't make any distinctions so it looks for C, C++ and Fortran components. Here:
https://gitlab.kitware.com/cmake/cmake/-/merge_requests/4071
for more info.
These are the components available: `C, CXX, MPICXX and Fortran` so if Fortran is not needed (is not enabled as language at the top of CMakeLists.txt) you could think of just doing:
```
find_package(MPI REQUIRED
        COMPONENTS C CXX)
```
or similar.
Otherwise you could enable at the top as language and then keep the find_package for mpi as it is.

**Comment by marianoimperatore** [comment]
Hi,

so I tried to play adding/removing openmpi and mpich and the error persist in any case.
Then in tried to edit the CmakeList file adding fortran as language, and cmake went through (!) but I get another error:
-- Could NOT find MPI_CXX (missing: MPI_CXX_WORKS) 
CMake Error at /home/mariano/cmake-3.17.0-Linux-x86_64/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
  Could NOT find MPI (missing: MPI_CXX_FOUND) (found version "3.1")
Call Stack (most recent call first):
  /home/mariano/cmake-3.17.0-Linux-x86_64/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:445 (_FPHSA_FAILURE_MESSAGE)
  /home/mariano/cmake-3.17.0-Linux-x86_64/share/cmake-3.17/Modules/FindMPI.cmake:1717 (find_package_handle_standard_args)
  CMakeLists.txt:71 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/mariano/Programs/espressopp/CMakeFiles/CMakeOutput.log".
See also "/home/mariano/Programs/espressopp/CMakeFiles/CMakeError.log".

so now it cannot find MPI_CXX or MPI at all...

Then, I tried to use spack to install it, and it went smooth till installing boost and failed immediately afterwards. I have created an issue on spack on this issue also.
