### ISSUE TITLE
Parallelization

### ISSUE THREAD

**Issue by almeida85** [espressopp/espressopp#306]
Hi all,

I started to learn how to use Espresso++, especially for AdresS. I am running the `hadress_water` example in a workstation with 8 cores and it doesn't see parallelized, it runs very slow as in a single CPU. Do I need to modify the script with PMI to make it parallel? 

Thanks in advance.

Best regards,
Yasser

**Comment by jkrajniak** [comment]
Hi Yasser,

Could you please share the command you used to run E++ in parallel?

**Comment by almeida85** [comment]
Hi, I didn't use any command. I just executed `./water.py`. My question was because the output shows the results of each frame very slow.

**Comment by jkrajniak** [comment]
OK, so to run the parallel version you have to use MPI, and e.g. run `mpirun -n 8 python ./water.py`

**Comment by almeida85** [comment]
Thanks! It seems to work, but still, it feels slower than expected. How does E++ scale? Is there any reference/graph about that?

**Comment by almeida85** [comment]
The job stopped with the following error:

```
0.49900       2.5038576       18666.145       11204.942       36700.441      -183483.68       58409.989 -58502.16536952

0.49950       2.5081319       18572.495       11216.664       36703.461      -183543.64       58509.701 -58541.31509937

Traceback (most recent call last):
  File "/mnt/data/yalmeida/Softwares/Espresso++/espressopp-1.9.5/examples/adress/hadress_water/water.py", line 259, in <module>
    sys.stdout.write('Neighbor list builds = %d\n' % vl.builds)
NameError: name 'vl' is not defined
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[63156,1],0]
  Exit code:    1
```
Any thoughts?

**Comment by jkrajniak** [comment]
> The job stopped with the following error:
> 
> ```
> 0.49900       2.5038576       18666.145       11204.942       36700.441      -183483.68       58409.989 -58502.16536952
> 
> 0.49950       2.5081319       18572.495       11216.664       36703.461      -183543.64       58509.701 -58541.31509937
> 
> Traceback (most recent call last):
>   File "/mnt/data/yalmeida/Softwares/Espresso++/espressopp-1.9.5/examples/adress/hadress_water/water.py", line 259, in <module>
>     sys.stdout.write('Neighbor list builds = %d\n' % vl.builds)
> NameError: name 'vl' is not defined
> -------------------------------------------------------
> Primary job  terminated normally, but 1 process returned
> a non-zero exit code.. Per user-direction, the job has been aborted.
> -------------------------------------------------------
> --------------------------------------------------------------------------
> mpirun detected that one or more processes exited with non-zero status, thus causing
> the job to be terminated. The first process to do so was:
> 
>   Process name: [[63156,1],0]
>   Exit code:    1
> ```
> 
> Any thoughts?

It seems to be a bug in the example. I have fixed it here https://github.com/espressopp/espressopp/pull/307

**Comment by jkrajniak** [comment]
> Thanks! It seems to work, but still, it feels slower than expected. How does E++ scale? Is there any reference/graph about that?

You can check the scaling in the original paper of E++ (http://dx.doi.org/10.1016/j.cpc.2012.12.004) and here https://www.sciencedirect.com/science/article/pii/S0010465518304399
But from my experience with different simulation packages (LAMMPS, GROMACS, E++), E++ had an issue with performance. AFAIK the focus was put on extensibility and next on the performance.

**Comment by almeida85** [comment]
Yes, I had the same feeling when I started playing with E++ in comparison with GROMACS and NAMD. Still, I think I will keep digging in it because it seems that is the best to do AdresS. The implementation in GROMACS is not easy to use and is poorly documented.
From the previous error, I just commented the line 259 and it was fine.
Thanks.

**Comment by govarguz** [comment]
Hi there,  an indeed useful reference is:
https://doi.org/10.1103/PhysRevE.96.053311
 While also, of you would like to use AdResS or H-AdResS you have to
consider the Hybrid region which may not allow any code to scale as
homogeneous MD.

Best,
Horacio

**Comment by almeida85** [comment]
Thanks a lot! That's very helpful!
Best,
Yasser

> Hi there, an indeed useful reference is: https://doi.org/10.1103/PhysRevE.96.053311 While also, of you would like to use AdResS or H-AdResS you have to consider the Hybrid region which may not allow any code to scale as homogeneous MD. Best, Horacio

**Comment by junghans** [comment]
> The implementation in GROMACS is not easy to use and is poorly documented.
See https://e-cam.readthedocs.io/en/latest/Meso-Multi-Scale-Modelling-Modules/index.html#gc-adress and section 6.12 of http://ftp.gromacs.org/pub/manual/manual-5.1.5.pdf for the documentation of AdResS in Gromacs.

**Comment by almeida85** [comment]
Hi junghans,

I've been playing with the GC-AdresS example from the E-CAM site and posted a question some days ago in the Github forum:[https://github.com/E-CAM/E-CAM-Library/issues/1](url). 

Thanks anyways

> > The implementation in GROMACS is not easy to use and is poorly documented.
> > See https://e-cam.readthedocs.io/en/latest/Meso-Multi-Scale-Modelling-Modules/index.html#gc-adress and section 6.12 of http://ftp.gromacs.org/pub/manual/manual-5.1.5.pdf for the documentation of AdResS in Gromacs.

**Comment by XzzX** [comment]
Resolved?

**Comment by XzzX** [comment]
Reopen if problem still persists.
