### ISSUE TITLE
"Warning! FixedTripleListInteractionTemplate does not work."

### ISSUE THREAD

**Issue by almeida85** [espressopp/espressopp#308]
Hello,

I am playing with the example for AdresS water (`hadress_water`), varying the AdResS dimensions (`ex_size, hy_size`). Also, I modified the script to calculate the density and pressure of the box, according to the `hadress.py` script (`hadress_tetraliquid/hadress_tetraliquid_plain`). When running the scripts I got the following warning:
```
Warning! At the moment computeVirialX in FixedTripleListInteractionTemplate does not work.
Therefore, the corresponding interactions won't be included in calculation.
```
I am running the script as `mpirun -n N ./water.py` and get this warning N times after each step.

What's the reason of this warning?

Thanks in advance.

Best,
Yasser

**Comment by jkrajniak** [comment]
Hi, it simply means that the method `computeVirialX` is not implemented for triple interactions (angle).  Not sure if this method is implemented anywhere.

**Comment by almeida85** [comment]
Thanks
