### ISSUE TITLE
Boost.Python.ArgumentError

### ISSUE THREAD

**Issue by almeida85** [espressopp/espressopp#314]
Hello,

I am trying to run the script `example/adress/hadress_water/water.py` and I get this error:
```
i*timestep, T, Eb, EAng, ELj, EQQ, Ek, Etotal
0.00000       2.5039415       19089.087       11405.327       32540.788      -181321.16       58411.947 -59874.01630923

Traceback (most recent call last):
  File "./water.py", line 257, in <module>
    integrator.run(steps/check) # print out every steps/check steps
  File "/mnt/d/Softwares/Espresso/espressopp-master/build/espressopp/pmi.py", line 668, in caller
    return _backtranslateProxy(call(method, *args, **kwargs))
  File "/mnt/d/Softwares/Espresso/espressopp-master/build/espressopp/pmi.py", line 383, in call
    return cfunction(*cargs, **ckwds)
  File "/mnt/d/Softwares/Espresso/espressopp-master/build/espressopp/pmi.py", line 1085, in __call__
    return self.method(*args, **kwds)
  File "/mnt/d/Softwares/Espresso/espressopp-master/build/espressopp/integrator/MDIntegrator.py", line 58, in run
    return self.cxxclass.run(self, niter)
Boost.Python.ArgumentError: Python argument types in
    integrator_MDIntegrator.run(VelocityVerletLocal, float)
did not match C++ signature:
    run(espressopp::integrator::MDIntegrator {lvalue}, int)
```
I have Boost 1.71 installed. It seems like `integrator_MDIntegrator.run(...)` pass a `float` and C++ `run(...)` expect an `int`.

Something similar happens in the script in lines 122 and line 240. I had to change them as:
```
.
.
.
for pidCG in range(int(num_particlesCG)):
.
.
.
for i in range(int(check)):
```

Bugs?

**Comment by jnvance** [comment]
Try changing `steps/check` to ``steps//check`. Python3 uses `/` for floating point division and `//` for integer division.

**Comment by almeida85** [comment]
> Try changing `steps/check` to `steps//check`. Python3 uses `/` for floating point division and `//` for integer division.

I did it but the error persists.

**Comment by jnvance** [comment]
And also the same for `check = steps//1` and `num_particlesCG = len(x)//3`. I'll submit a PR later to fix these.

**Comment by almeida85** [comment]
> And also the same for `check = steps//1` and `num_particlesCG = len(x)//3`. I'll submit a PR later to fix these.

Done, it worked.
Thanks!
