### ISSUE TITLE
E++ compilation in a cluster

### ISSUE THREAD

**Issue by almeida85** [espressopp/espressopp#315]
Hi,

I trying to compile E++ in an HPC cluster. Inspecting the `CMakeCache.txt` file I saw all the flags and MPI variables that in principle can be used to customize the compilation. My cluster runs the SLURM queue system. I use `mpirun` for parallelization.

1 - Could anyone give an example of options to compile E++ for a cluster?
2 - Is E++ designed to run in GPUs?

Thanks.

**Comment by jkrajniak** [comment]
Hi,

1. It mostly depends on the compiler and the cluster architecture, e.g. for Intel compiler I often used `-O2  -xAVX -axCORE-AVX2,CORE-AVX512`

2. AFAIK E++ does not utilize GPU at all.

Best, Jakub

**Comment by almeida85** [comment]
Hi,
Thank you for the reply.

For CXX compiler I am using C++ compiler (GCC 4.8.5 20150623 (Red Hat 4.8.5-39)), in a cluster with CentOS Linux 7 x86_64. 

My cluster has:
1 Frontend node:
– 56 TByte net storage (17 x 4 TByte SATA HDDs, RAID array, level 6)
– 2 CPUs / 24 cores per node (CPU: Intel Xeon Skylake Gold 6126 with 2.6 GHz, 12 cores/24 threads)
– 192 Gbyte RAM per node (8 Gbyte / core)

20 computation nodes:
– 16 nodes: Intel Xeon Gold 6126 with 2x12 Cores,192 GB RAM, 2 TB storage
– 4 nodes: Intel Xeon Gold 6130 with 2x16 Cores, 96 GB RAM, 6,5T storage

... plus 2 GPUs nodes. Which variables are the most appropriate for these settings? I am pretty new compiling customized codes in clusters.

Is `CMAKE_CXX_FLAGS_RELEASE:STRING=` the variable to insert the corresponding flags?

Best,
Yasser

**Comment by almeida85** [comment]
... I also use `mpicxx` as MPI C++ wrapper.

**Comment by jkrajniak** [comment]
I would try simply with `-O2` or `-O3` and compare the execution times; yes, you can put additional flags in that variable.

**Comment by XzzX** [comment]
Is this resolved?
