### ISSUE TITLE
Error during linking

### ISSUE THREAD

**Issue by buesingh** [espressopp/espressopp#321]
Hi, 

I try to compile espressopp. Everything works out fine until linking phase when I get an error (see footnote [1] below). Any ideas what could be wrong?
Thank you!

[1]

[ 87%] Linking CXX executable PTestDomainDecomposition
../_espressopp.so: error: undefined reference to 'boost::python::detail::gcc_demangle(char const*)'
collect2: Fehler: ld gab 1 als Ende-Status zurück
make[2]: *** [testsuite/CMakeFiles/PTestDomainDecomposition.dir/build.make:116: testsuite/PTestDomainDecomposition] Fehler 1
make[1]: *** [CMakeFiles/Makefile2:1423: testsuite/CMakeFiles/PTestDomainDecomposition.dir/all] Fehler 2
make: *** [Makefile:160: all] Fehler 2

**Comment by XzzX** [comment]
Is this resolved?

**Comment by XzzX** [comment]
Reopen if problem still persists.
