### ISSUE TITLE
CI is failing for current master

### ISSUE THREAD

**Issue by XzzX** [espressopp/espressopp#327]
fedora images do not have a proper mpi4py installation:  
 - [ ] https://travis-ci.org/github/espressopp/espressopp/jobs/766333270#L346

opensuse images have multiple issues:
  
- [ ] h5py build without mpi support
https://travis-ci.org/github/espressopp/espressopp/jobs/766333272#L5210
- [ ] problems while writing output files
https://travis-ci.org/github/espressopp/espressopp/jobs/766333272#L5160

**Comment by junghans** [comment]
I think https://github.com/espressopp/buildenv has failed to build for a long time and hence the containers aren't really up to date and super-outdated.

First step might be to fix that and see what it helps.

**Comment by junghans** [comment]
Also Travis CI is basically dead, we might want to switch to GitHub actions instead.

**Comment by XzzX** [comment]
> I think https://github.com/espressopp/buildenv has failed to build for a long time and hence the containers aren't really up to date and super-outdated.
> 
> First step might be to fix that and see what it helps.

At least the fedora image was built successfully three days ago.
