### ISSUE TITLE
user specific search path?

### ISSUE THREAD

**Issue by XzzX** [espressopp/espressopp#328]
https://github.com/espressopp/espressopp/blob/05ae583ddabb47e959f867fc0b7539c6af2bd599/CMakeLists.txt#L53

Should be replaced by a proper search for `VampirTrace`.

**Comment by junghans** [comment]
No no that is a feature that only @stuehn is supposed to use ;-)

**Comment by stuehn** [comment]
This is outdated since a few years. I am not even sure if we still need VAMPIRTRACE here, we have other tools for that purpose now.

**Comment by XzzX** [comment]
Since the current implementation only works for you I propose removing it.
