### ISSUE TITLE
Issues with different combinations of boost, gcc, apple clang, etc

### ISSUE THREAD

**Issue by niktre** [espressopp/espressopp#34]
Hi! I wasn't sure whether to re-open #8 or start a new issue.. 
I have a pleasure of using a MacBook and therefore have additional fun compiling ESPResSo++, but it is interesting NOT only for Mac users:
Boost: external 1.59.0
MPI4PY: internal
c / c++: from Apple (clang 7.0.0)
c / c++ flags: -std=c99 / -std=c++03 

The error I get when compiling:
Linking CXX shared library ../_espressopp.so
Undefined symbols for architecture x86_64:
  "boost::system::system_category()", referenced from:
      __GLOBAL__sub_I_bindings.cpp in bindings.cpp.o
      __GLOBAL__sub_I_DumpGRO.cpp in DumpGRO.cpp.o
      __GLOBAL__sub_I_DumpGROAdress.cpp in DumpGROAdress.cpp.o
      __GLOBAL__sub_I_DumpXYZ.cpp in DumpXYZ.cpp.o
  "boost::system::generic_category()", referenced from:
      __GLOBAL__sub_I_bindings.cpp in bindings.cpp.o
      __GLOBAL__sub_I_DumpGRO.cpp in DumpGRO.cpp.o
      __GLOBAL__sub_I_DumpGROAdress.cpp in DumpGROAdress.cpp.o
      __GLOBAL__sub_I_DumpXYZ.cpp in DumpXYZ.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [_espressopp.so] Error 1
make[1]: *** [src/CMakeFiles/_espressopp.dir/all] Error 2
make: *** [all] Error 2

If I switch to internal Boost, everything is fine!

**Comment by junghans** [comment]
Does that help? (`git pull https://github.com/junghans/espressopp.git master`)

**Comment by junghans** [comment]
Somebody needs to look into that: <https://docs.travis-ci.com/user/osx-ci-environment/>

**Comment by niktre** [comment]
Sorry Christoph, I will be able to check if it works only on Tuesday..

**Comment by niktre** [comment]
Christoph, your suggestion helps with the compilation, but when I ran ESPResSo++ I get an error with MPI (it is basically what was announced by @pdebuyl in #8). However, when I do ```otool -L ../../_espressopp.so``` to check paths of used libraries, I get problems not only with libboost_mpi.dylib, but ALL of boost libraries:
```
niktre@MacBook-Pro:~/Software/myFork_espressopp$ otool -L _espressopp.so 
_espressopp.so:
	/Users/niktre/Software/myFork_espressopp/_espressopp.so (compatibility version 0.0.0, current version 0.0.0)
	libboost_mpi.dylib (compatibility version 0.0.0, current version 0.0.0)
	libboost_python.dylib (compatibility version 0.0.0, current version 0.0.0)
	libboost_serialization.dylib (compatibility version 0.0.0, current version 0.0.0)
	libboost_system.dylib (compatibility version 0.0.0, current version 0.0.0)
	libboost_filesystem.dylib (compatibility version 0.0.0, current version 0.0.0)
	/System/Library/Frameworks/Python.framework/Versions/2.7/Python (compatibility version 2.7.0, current version 2.7.10)
	/usr/local/lib/libmpi_cxx.1.dylib (compatibility version 2.0.0, current version 2.2.0)
	/usr/local/lib/libmpi.1.dylib (compatibility version 2.0.0, current version 2.8.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1225.1.1)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.1.0)
```

I.e. the ```_espressopp.so``` thinks they are in the same directory as itself, but they are NOT. Unfortunately, when I re-reference the libraries via, for example, 
```install_name_tool -change libboost_mpi.dylib /where_I_have_external_boost/lib/libboost_mpi.dylib _espressopp.so```
the same the problem with serialization library persists.

My conclusion: problem with running ESPResSo++ with external boost (v. 1.59.0) does not need the mpi library to be compiled with a new gcc (v. >= 5.2), but rather re-referencing correct paths to boost libraries. Why the paths are not there from the beginning is not clear to me...

**Comment by junghans** [comment]
If the fix helps compilation I guess we should merge it.

Concerning the runtime issue, we might need to inject `/where_I_have_external_boost/lib` into DYLD_LIBRARY_PATH in `ESPRC`.

**Comment by niktre** [comment]
By the way, I've just noticed that even though include and library directories of external boost are found by cmake, there is the following:
``` Boost_DIR                        Boost_DIR-NOTFOUND```

Could it be the source of confusion for a wrong place of linked libraries?

**Comment by junghans** [comment]
No, `Boost_DIR` is just a variable, you can use to hint cmake to some obscure directory where boost is installed and you have simply not used that variable.

**Comment by junghans** [comment]
Btw, which cmake version are you using? For rpath support on OSX (which is needed to make `_espressopp.so` remember where it found libboost in a non-standard place) one needs at least cmake 2.8.12:  http://www.kitware.com/blog/home/post/510

**Comment by niktre** [comment]
I have an El Capitan and newest Command Line Tools installed. There it is ```cmake version 2.8.12.2```

**Comment by junghans** [comment]
That is very close, could you try a newer version like https://cmake.org/files/v3.4/cmake-3.4.1-Darwin-x86_64.dmg from the cmake website.

**Comment by niktre** [comment]
By the way, can we use more checks in travis? Different versions of gcc, boost and, maybe, intel compiler could be very nice...
Shouldn't we switch to internal Boost and MPI4PY by default? It is strange to always specify them when compiling and if a user is experienced and wants a very new Boost or MPI4PY he will find a way to change to external ones.

**Comment by junghans** [comment]
Sure, I am all for more testing! I started that here: <https://github.com/espressopp/espressopp/compare/master...junghans:new_gcc>

However I would vote for leaving external the default, mainly because it becomes super-messy if you load another python module link again another boost library or use mpi4py with a different mpi. Using the system ones seems a little bit more save to me.

**Comment by niktre** [comment]
Ok, I see. Maybe it is really then at the moment better to rely on external ones..

Christoph, a simple question. How can I get these changes that you have in new_gcc branch? I understand I can simply copy-paste, but is there another more elegant way (maybe through pull request)?

**Comment by junghans** [comment]
You can do `git pull git@github.com:junghans/espressopp new_gcc`.

**Comment by niktre** [comment]
Cool thank you!

**Comment by junghans** [comment]
Should we merge 4b27c4615437a40046d843be0a8e5a6cedba532b?
