### ISSUE TITLE
enable CCache in GitHub actions

### ISSUE THREAD

**Issue by XzzX** [espressopp/espressopp#343]

**Comment by junghans** [comment]
Done in #344

**Comment by XzzX** [comment]
> Done in #344

Please add `closes #343` to your PR. This way round it will automatically close this issue and link the PR. It will also automatically move the issue forward in our code quality project https://github.com/espressopp/espressopp/projects/5

**Comment by junghans** [comment]
Still need to enable it for Intel compilers
