### ISSUE TITLE
Check if hdf5 is parallel at CMake time

### ISSUE THREAD

**Issue by junghans** [espressopp/espressopp#346]
Currently everything will build, but then the test fails with an error that hdf5 is not parallel

**Comment by XzzX** [comment]
I cannot find evidence of `hdf5` in our code. Do you mean `h5py`?

**Comment by junghans** [comment]
it is an error that h5py prints out.

**Comment by XzzX** [comment]
Shameless advertisement, use my new H5MD parallel dump and restore which I will create a PR for soon. :D It handles both, parallel and non-parallel installations.
