### ISSUE TITLE
fix install in CMake

### ISSUE THREAD

**Issue by junghans** [espressopp/espressopp#349]

**Comment by junghans** [comment]
@XzzX what was actually broken here?

**Comment by XzzX** [comment]
I did not dig into it. If I remember correctly there is an issue with `ESPRC`.

**Comment by junghans** [comment]
`ESPRC` sets `PYTHONPATH` if you source it, I don't see what is wrong with that.

The one is `build/ESPRC` is the one to use espresso++ in place, the one in `build/src/ESPRC` is the one that will be installed.
Both have different paths, but the correct ones as far as I can see.

**Comment by XzzX** [comment]
I do not remember. Let's see. #357
