### ISSUE TITLE
drop internal mpi4py? 

### ISSUE THREAD

**Issue by junghans** [espressopp/espressopp#351]

**Comment by XzzX** [comment]
https://github.com/espressopp/espressopp/blob/a967dada2b0fda6d390b89abcdc1f1541068d823/src/System.cpp#L52-74

This is the only reference of `mpi4py` in the C++ code. Coupling would be much cleaner if just `MPI_Comm` was passed. However, I have no clue how `mpi` is wrapped through `mpi4py` is wrapped through `pmi` and passed to the backend.

@stuehn Can we couple with `MPI_Comm` here?

After refactoring this part I am ok with dropping our custom `mpi4py`.

**Comment by junghans** [comment]
Everything seems to work with v2 and v3, so couldn't we just check the detected version in CMake?

**Comment by junghans** [comment]
Seeing the most recent problems with our internal mpi4py, I think we need a CI container without mpi4py to test this more in depth.

**Comment by XzzX** [comment]
We should couple via a native MPI type and not via some mpi4py struct. This way our C++ code would be independent of mpi4py.
see #396

**Comment by junghans** [comment]
After #396 is merged, can we now drop the internal `mpi4py` and install it via `requirements.txt`?

**Comment by XzzX** [comment]
Yes, I think so. I will provide a PR.
