### ISSUE TITLE
proper error handling

### ISSUE THREAD

**Issue by XzzX** [espressopp/espressopp#379]
https://github.com/espressopp/espressopp/blob/4aa99d9e58b1b002e0c7083e2692c39af9dff895/src/bc/OrthorhombicBC.cpp#L143-L146

https://github.com/espressopp/espressopp/blob/4aa99d9e58b1b002e0c7083e2692c39af9dff895/src/bc/SlabBC.cpp#L143-L146

@junghans @jnvance Can we just throw here. The current construct helps no one.

**Comment by jnvance** [comment]
I agree. They probably intended to use one of the internal error handling methods such as LOG4ESPP_ERROR.
