### ISSUE TITLE
opensuse build fails

### ISSUE THREAD

**Issue by junghans** [espressopp/espressopp#423]
```
-- HDF5 C compiler wrapper is unable to compile a minimal HDF5 program.
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:[23](https://github.com/espressopp/espressopp/runs/5429930182?check_suite_focus=true#step:6:23)0 (message):
-- Configuring incomplete, errors occurred!
  Could NOT find HDF5 (missing: HDF5_LIBRARIES HDF5_INCLUDE_DIRS
See also "/__w/espressopp/espressopp/build/CMakeFiles/CMakeOutput.log".
  HDF5_HL_LIBRARIES C HL) (found version "")
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindHDF5.cmake:1001 (find_package_handle_standard_args)
  CMakeLists.txt:70 (find_package)
```

**Comment by junghans** [comment]
I guess we need to add a path here: https://github.com/espressopp/buildenv/blob/1826da1ffc6685bcf6c70844f067323e99277226/opensuse#L20

**Comment by XzzX** [comment]
pipeline which is failing: https://github.com/espressopp/espressopp/actions/runs/2007092318

**Comment by junghans** [comment]
Now it fails in a different way: https://github.com/espressopp/espressopp/runs/5879274758?check_suite_focus=true

**Comment by XzzX** [comment]
I know this problem: https://github.com/XzzX/mrmd/commit/a520795c74bf6da4a1fc5b8fcea509a66668423f

Release version of HDF5 enforces `_FORTIFY_SOURCE` on all its dependencies. And `_FORTIFY_SOURCE` requires optimizations flags. Therefore, it produces warnings when build in debug mode without optimization. Do we have debug libraries for HDF5?

**Comment by junghans** [comment]
@XzzX next one:
```
In file included from /__w/espressopp/espressopp/src/interaction/LJcos.cpp:25:
/__w/espressopp/espressopp/src/interaction/VerletListAdressInteractionTemplate.hpp:1091:25: error: 'bind2nd<std::divides<double>, double>' is deprecated: use 'std::bind' instead [-Werror,-Wdeprecated-declarations]
                   std::bind2nd(std::divides<real>(), Volume));
                        ^
/usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/backward/binders.h:170:5: note: 'bind2nd<std::divides<double>, double>' has been explicitly marked deprecated here
    _GLIBCXX11_DEPRECATED_SUGGEST("std::bind")
    ^
```

**Comment by XzzX** [comment]
#428

**Comment by XzzX** [comment]
Next round:
https://github.com/espressopp/espressopp/runs/6274009088?check_suite_focus=true

`h5py was built without MPI support, can't use mpio driver`

@junghans Did you change anything about the h5py installation? This is an old test from the previous H5MD interface. It explicitly selects `mpio`.

**Comment by junghans** [comment]
In the ubuntu container:
```
$ ipython3
import pyh5md
pyh5md.File('file.txt', "w",driver='mpio')

ValueError: h5py was built without MPI support, can't use mpio driver
```

**Comment by junghans** [comment]
I think the problem is in `usr/lib/python3/dist-packages/h5py/__init__.py`:
```
_OPENMPI_MULTIPROC = os_getenv('OMPI_COMM_WORLD_SIZE') is not None
_MPICH_MULTIPROC = os_getenv('MPI_LOCALNRANKS') is not None
_MPI_USE_ALWAYS = os_getenv('H5PY_ALWAYS_USE_MPI') is not None

_MPI_ACTIVE = _OPENMPI_MULTIPROC or _MPICH_MULTIPROC or _MPI_USE_ALWAYS

if _MPI_ACTIVE:
    try:
        from . import _debian_h5py_mpi as _h5py
    except:
        from . import _debian_h5py_serial as _h5py
else:
    from . import _debian_h5py_serial as _h5py
```

I guess we have to set `H5PY_ALWAYS_USE_MPI`.

**Comment by junghans** [comment]
In the ubuntu container:
```
$ ipython3
import pyh5md
pyh5md.File('file.txt', "w",driver='mpio')

ValueError: h5py was built without MPI support, can't use mpio driver
```

**Comment by junghans** [comment]
https://github.com/espressopp/buildenv/commit/9687442f2d17cc0021267888effdba7b9d2e3a67

**Comment by junghans** [comment]
I made some progress: https://github.com/espressopp/espressopp/actions/runs/2267132297

`ubuntu_devel` is broken due to some rebuild they currently do.....
see: https://github.com/espressopp/buildenv/runs/6281675179?check_suite_focus=true
