### ISSUE TITLE
Do we need Pipfile and Pipfile.lock?

### ISSUE THREAD

**Issue by XzzX** [espressopp/espressopp#437]
I am not too familiar with Python environments. Is `requirements.txt` enough? @junghans 

The dependabot warning concerns these two files.

**Comment by junghans** [comment]
Me neither@jkrajniak added those, he might know.

**Comment by XzzX** [comment]
I suggest removing the files. You can install all dependencies via requirements.txt in all Python environments.

**Comment by XzzX** [comment]
I suggest removing the files due to lack of maintainers. I also think in all environments missing packages can be installed via `requirements.txt`. See #439
