### ISSUE TITLE
Make Error: Linking CXX executable RealNDTest

### ISSUE THREAD

**Issue by JessLJY** [espressopp/espressopp#497]
Hi there, I used git clone and followed the Quick Install instructions on the ReadMe page and there were no errors during the cmake command. However, during the make command, I keep running into the following error and am hence perplexed as to how to approach this. I am a bit apprehensive to be changing file paths etc since this concerns cmake built files. I would really appreciate some advice on how I may resolve this, thank you! 

`[ 84%] Linking CXX shared library ../_espressopp.so`
`[ 84%] Built target _espressopp`
`[ 85%] Building CXX object testsuite/CMakeFiles/RealNDTest.dir/RealNDTest/RealNDTest.cpp.o`
`[ 85%] Linking CXX executable RealNDTest`
`/usr/bin/ld: cannot open output file RealNDTest: Is a directory`
`collect2: error: ld returned 1 exit status`
`make[2]: *** [testsuite/CMakeFiles/RealNDTest.dir/build.make:108: testsuite/RealNDTest] Error 1`
`make[1]: *** [CMakeFiles/Makefile2:697: testsuite/CMakeFiles/RealNDTest.dir/all] Error 2`
`make: *** [Makefile:146: all] Error 2`

**Comment by junghans** [comment]
Can you do a `make VERBOSE=1` and post the complete error message?

**Comment by junghans** [comment]
See my fix in #498 for now just do an out-of-source build:
```
cmake -B builddir .
cmake --build builddir
```

**Comment by JessLJY** [comment]
Thanks so much for the fix, really appreciate it!
