### ISSUE TITLE
Travis building fails

### ISSUE THREAD

**Issue by niktre** [espressopp/espressopp#71]
Hi,
I am not sure what is happening but all my travis compilations fail with these two messages:

Coverity Scan analysis selected for branch master.
Coverity Scan API access denied. Check $PROJECT_NAME and $COVERITY_SCAN_TOKEN.

[https://travis-ci.org/niktre/espressopp/jobs/117255851]

What does it want from me? :-)

**Comment by junghans** [comment]
It means the coverity scan doesn't work in your fork, but as Coverity is too slow to analyse Espresso++ maybe we should drop that part from `.travis.yml` again!
